In [1]:
import cx_Oracle
import pandas as pd
import os
import pyarrow.parquet as pq

In [37]:
%%time
# Source database connection
source_conn = cx_Oracle.connect(
    user="apps",
    password="apps",
    dsn="csebsd2db.cswg.com:1521/csebsd2_int"
)
source_cursor = source_conn.cursor()


# Read the query from the file
with open('CM_full_cursor.sql', 'r') as file:
    query = file.read()

source_cursor.execute(query)
df = source_cursor.fetchall()

# Create a DataFrame from the fetched data
columns_info = [(desc[0], desc[1]) for desc in source_cursor.description]
columns_multiindex = pd.MultiIndex.from_tuples(columns_info, names=['ColumnName', 'DataType'])
cust_df = pd.DataFrame(df, columns=columns_multiindex)


# Display the data
print("The DataFrame of GTT:")
print(cust_df)

# Write the DataFrame to a Parquet file
# cust_df.to_parquet('CM_full_cursor.parquet', index=False)
# # [2397 rows x 316 columns]
# # Wall time: 1min 15s

# # Read data from the Parquet file
# df_gtt = pd.read_parquet('CM_full_cursor.parquet')
# print(df_gtt)

The DataFrame of GTT:
ColumnName                     PARTY_SITE_ID  \
DataType   <cx_Oracle.DbType DB_TYPE_NUMBER>
0                                      25275
1                                     376902
2                                     376998
3                                     376999
4                                     377000
...                                      ...
2392                                 3467192
2393                                 3470193
2394                                 3470194
2395                                 3470195
2396                                 3470196

ColumnName                          STORE_NBR  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                       20054
1                                       25317
2                                       25401
3                                       25403
4                                       25415
...                                       ...
2392                                    45018
2393                                947230-MX
2394                                947244-MX
2395                                947291-MX
2396                                947886-MX

ColumnName                         STORE_NAME  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                   BLACKIE'S FARM FRESH PROD
1                          FAIRWAY E-COMMERCE
2                      IMPERIAL BAGS PAPER CO
3                      N & P FOOD SERVICES IN
4                      PLAINFIELD TOB & CANDY
...                                       ...
2392                    JIB #8203- UMI STREET
2393                    SEVEN UP CO DSD 13200
2394                  FRITO LAY INC DSD 80024
2395                    BERRES BROTHER COFFEE
2396                           ANHEUSER BUSCH

ColumnName                       STORE_STATUS              STORE_BILL_TO_FLAG  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR> <cx_Oracle.DbType DB_TYPE_CHAR>
0                                      Active                               Y
1                                      Active                               N
2                                      Active                               Y
3                                      Active                               Y
4                                      Active                               Y
...                                       ...                             ...
2392                                   Active                               N
2393                                   Active                               Y
2394                                   Active                               Y
2395                                   Active                               Y
2396                                   Active                               Y

ColumnName              STORE_SHIP_TO_FLAG                           ACCT_ID  \
DataType   <cx_Oracle.DbType DB_TYPE_CHAR> <cx_Oracle.DbType DB_TYPE_NUMBER>
0                                        Y                              6638
1                                        Y                            269082
2                                        Y                            248132
3                                        Y                            278045
4                                        Y                            278057
...                                    ...                               ...
2392                                     Y                           1594063
2393                                     N                           1597068
2394                                     N                           1597069
2395                                     N                           1597070
2396                                     N                           1597071

ColumnName                           ACCT_NBR  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                       20054
1                                          79
2                                       25401
3                                       25403
4                                       25415
...                                       ...
2392                                    45016
2393                                   947230
2394                                   947244
2395                                   947291
2396                                   947886

ColumnName                          ACCT_NAME  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                   BLACKIE'S FARM FRESH PROD
1                                     FAIRWAY
2                      IMPERIAL BAGS PAPER CO
3                      N & P FOOD SERVICES IN
4                      PLAINFIELD TOB & CANDY
...                                       ...
2392                         JACK IN THE BOX
2393                    SEVEN UP CO DSD 13200
2394                  FRITO LAY INC DSD 80024
2395                    BERRES BROTHER COFFEE
2396                           ANHEUSER BUSCH

ColumnName                        ACCT_STATUS  ...  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>  ...
0                                           A  ...
1                                           A  ...
2                                           A  ...
3                                           A  ...
4                                           A  ...
...                                       ...  ...
2392                                        A  ...
2393                                        A  ...
2394                                        A  ...
2395                                        A  ...
2396                                        A  ...

ColumnName                     GS_SUPER_SERVE  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                         GS_NABISCO  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                       GS_WILL_CALL  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                              SWELL  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                            HQ_FLAG  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName               GS_PRIMARY_SHIP_FLAG  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                       GS_FUEL_ZONE  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                  GS_FUEL_ZONE_DESC  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName                   GS_AD_GROUP_DESC  \
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

ColumnName               GS_PRICING_ZONE_DESC
DataType   <cx_Oracle.DbType DB_TYPE_VARCHAR>
0                                        None
1                                        None
2                                        None
3                                        None
4                                        None
...                                       ...
2392                                     None
2393                                     None
2394                                     None
2395                                     None
2396                                     None

[2397 rows x 316 columns]
Wall time: 32 s

In [17]:
# Accessing column names and data types
column_names = cust_df.columns.get_level_values('ColumnName')
data_types = cust_df.columns.get_level_values('DataType')

# Printing column names and data types
print("Column Names:", list(column_names))
print("Data Types:", list(data_types))

Column Names: ['PARTY_SITE_ID', 'STORE_NBR', 'STORE_NAME', 'STORE_STATUS', 'STORE_BILL_TO_FLAG', 'STORE_SHIP_TO_FLAG', 'ACCT_ID', 'ACCT_NBR', 'ACCT_NAME', 'ACCT_STATUS', 'ACCT_CUST_CLASS_CODE', 'ACCT_CREATION_DATE', 'CHAIN_NBR', 'CHAIN_NAME', 'CHAIN_SHORT_NAME', 'CHAIN_INACTIVE_DATE', 'START_CUST_NBR', 'STRT_CUST_NBR2', 'END_CUST_NBR', 'END_CUST_NBR2', 'PRIVATE_LABEL_OFFSET', 'SUB_AUTH_OFFST', 'AD_START_DAY_OF_WEEK', 'COMPANY_CODE', 'HQ_CUST_NBR', 'DIVISION_NBR', 'DIVISION_NAME', 'EBS_GL_CUST_GROUP_NBR', 'EBS_GL_CUST_GROUP_NAME', 'STORE_GROUP_NBR', 'STORE_GROUP_NAME', 'GROUP_BUY_NBR', 'STORE_CREATION_DATE', 'STORE_INACTIVE_DATE', 'STORE_LAST_UPDATE_DATE', 'LOCATION_ID', 'STORE_ADDRESS1', 'STORE_ADDRESS2', 'STORE_ADDRESS3', 'STORE_ADDRESS4', 'STORE_CITY', 'STORE_POSTAL_CODE', 'STORE_STATE', 'STORE_PROVINCE', 'STORE_COUNTY', 'STORE_COUNTRY', 'STORE_TELEPHONE_NBR', 'CUST_STORE_NBR', 'CUST_ACCT_PROFILE_ID', 'PAY_TERMS', 'PAY_TERM_DESC', 'PAY_TERM_START_DATE', 'PAY_TERM_END_DATE', 'COLLECTOR_NAME', 'STATEMENT_CYCLE_NAME', 'ALT_CUST_NBR', 'BASE_CUST_NBR', 'CUST_STATEMENT_FORMAT', 'PACA_FLAG', 'TOBACCO_BILLABLE_FLAG', 'TOBACCO_REBATE', 'ZONE_NBR', 'MILITARY_DODAAC', 'SALES_REPRESENTATIVE', 'BILL_TO_STORE_NBR', 'BILL_TO_STORE_NAME', 'PRIMARY_CONTACT_NAME', 'PRIMARY_CONTACT_PHONE_NBR', 'PRIMARY_CONTACT_EMAIL_ADDR', 'CUSTOMER_GROUP', 'STORE_GROUP', 'FINANCE_CHARGES', 'INTEREST_RATE', 'PAYMENT_GRACE_DAYS', 'INTEREST_PERIOD_DAYS', 'STATEMENT_ADDRESS1', 'STATEMENT_CITY', 'STATEMENT_STATE', 'STATEMENT_ZIP', 'FINANCE_CHARGE_EFFECTIVE_DATE', 'SUMMARY_STMT_FORMAT', 'DELINQUENT_START_DATE', 'AR_SEGMENT_GROUP', 'AR_GROUP_NAME', 'IMPORTED_SOURCE', 'REMITTANCE_ADDR', 'STATEMENT_TOLRNCE', 'INVOICE_TOLRNCE', 'SALES_REP', 'RISK_TIER', 'GS_RETAIL_ACCTNG_REPORT', 'STATEMENT_LEVEL', 'RELATED_CUST_LOCKBOX_APPLLY', 'SEND_ACH_NOTIFTN', 'STOCK_NAME', 'MULTI_STORE', 'EFT', 'PICKUP_DAY', 'PAY_DUE_DAY', 'CREDIT_HOLD', 'PAYMENT_TERMS', 'CREDIT_GROUP', 'BLANK_CHECK_CUSTOMER', 'AD_PLAN_GROUP', 'AWI_PARTY_SITE_ID', 'AWI_MULTI_STORE_NBR', 'PATRONAGE_NBR', 'PRINT_STATEMENTS', 'STATEMENT_INSTRUCTIONS', 'SEND_TO_AWI_CDH_FLG', 'CM_BILLING_CYCLE', 'CM_TERMS', 'CM_NP_XFER_FLAG', 'CM_PRINT_STMT', 'CM_RET_ACCT_STMT', 'CM_STMT_COPIES', 'CM_GROUP_CODE', 'CM_PAYMENT_METHOD', 'CM_STMT_LABELS', 'CM_PAYMENT_DUE_DAYS', 'CM_SUB_STORE', 'CM_CUST_XREF_NO', 'STMT_ADJ_GROUP_CODE', 'PSUEDOEPHEDRINE_FLAG', 'CALL_FOR_CUSTOMER', 'CIGARETTE_LICENSE', 'SMALL_PACK', 'CIGARETTE_VALIDATION', 'AWI_CDH_CUSTOMER_CLASS', 'GAS_REWARDS', 'MILES', 'PRINT_STMTS', 'AWI_CDH_RACK_SERVICE', 'RETAIL_TYPE', 'TAX_EXEMPT', 'ADV_FLAG_7', 'ADV_FLAG6', 'BB_AD_PLAN', 'AD_COMMENTS', 'ADV_FLAG5', 'CONFO_AD_PLAN', 'DEFAULT_TRIP', 'CATALOG10', 'AWI_PRINT_BULLETIN', 'AWI_SIGN_KIT', 'SURVEYS', 'ADV_FLAG8', 'AWI_AD_OFFSET', 'AGNE_CUSTOMER', 'CONFO', 'HBA_GM_FLAG', 'HBA_GM_DISC_OVERIDE', 'HBA_GM_DISC', 'ITEM_ALLOWANCE', 'COD', 'SERV_CHARGE', 'SINGLE_PICK', 'AWI_CUSTOMER_TYPE', 'MULTI_STORE_NUMBER', 'EIGHT_WEEK_BB', 'BB_MOD_PROGRAM', 'KPC_END', 'KPC_RETAIL_ZONE', 'KPC_START', 'AWI_PRODUCT', 'SPECIALTY_FOODS', 'D_COST_PLUS_BRACKET_FLAG', 'D_COST_PLUS_BRACKET_NUMBER', 'D_MERCHANDISER', 'D_PRICING_FLAG', 'D_SALESMAN', 'D_SKID_ROUNDING_FLAG', 'SY_COST_PLUS_BRACKET_FLAG', 'SY_COST_PLUS_BRACKET_NUMBER', 'SY_MERCHANDISER', 'SY_PRICING_FLAG', 'SY_SALESMAN', 'SY_SKID_ROUNDING_FLAG', 'M_COST_PLUS_BRACKET_FLAG', 'M_COST_PLUS_BRACKET_NUMBER', 'M_MERCHANDISER', 'M_PRICING_FLAG', 'M_SALESMAN', 'M_SKID_ROUNDING_FLAG', 'P_COST_PLUS_BRACKET_FLAG', 'P_COST_PLUS_BRACKET_NUMBER', 'P_MERCHANDISER', 'P_PRICING_FLAG', 'P_SALESMAN', 'P_SKID_ROUNDING_FLAG', 'GM_COST_PLUS_BRACKET_FLAG', 'GM_COST_PLUS_BRACKET_NUMBER', 'GM_MERCHANDISER', 'GM_PRICING_FLAG', 'GM_SALESMAN', 'GM_SKID_ROUNDING_FLAG', 'C_COST_PLUS_BRACKET_FLAG', 'C_COST_PLUS_BRACKET_NUMBER', 'C_MERCHANDISER', 'C_PRICING_FLAG', 'C_SALESMAN', 'C_SKID_ROUNDING_FLAG', 'F_COST_PLUS_BRACKET_FLAG', 'F_COST_PLUS_BRACKET_NUMBER', 'F_MERCHANDISER', 'F_PRICING_FLAG', 'F_SALESMAN', 'F_SKID_ROUNDING_FLAG', 'RG_COST_PLUS_BRACKET_FLAG', 'RG_COST_PLUS_BRACKET_NUMBER', 'RG_MERCHANDISER', 'RG_PRICING_FLAG', 'RG_SALESMAN', 'RG_SKID_ROUNDING_FLAG', 'DSD_VENDOR', 'CUST_CODE_XREF', 'SITE_PICK_SLIP_REQ', 'SITE_PICK_SLIP_REQ_DISP', 'SITE_RANK', 'ACC_SUBS', 'REJ_REASON', 'MAX_VOL_PALL', 'ITEM_PAL_ROUND', 'LOG_ORD_QTY', 'MIN_ORD_QTY', 'ENFORCE_DEPT', 'MAX_ORD_QTY', 'PO_REQ', 'PO_REQ_DISP', 'RET_PRC_REQ', 'RET_PRC_REQ_DISP', 'CUST_XREF', 'CUST_XREF_DISP', 'LEGACY_CUST_NBR', 'LEGACY_COMPANY', 'BILL_TO_SITE_USE_ID', 'SHIP_TO_SITE_USE_ID', 'HOSTING_DEPT', 'RETAILER_DEPT', 'CONTACT_INFO', 'STORE_MANAGER', 'STORE_OWNER', 'STORE_TYPE', 'ACCEPT_SUBS', 'INT_PO_REQ', 'DIVISION_ID', 'REGION', 'DELEGATE_AUTRIZTN_FLG', 'AISLE_LIMIT', 'ACCT_TYPE', 'OLD_STORE_NBR', 'GS_DASH_0', 'GS_DASH_0_DESCRIPTION', 'GS_DASH_1', 'GS_DASH_1_DESCRIPTION', 'GS_DASH_2', 'GS_DASH_2_DESCRIPTION', 'GS_DASH_3', 'GS_DASH_3_DESCRIPTION', 'GS_DASH_4', 'GS_DASH_4_DESCRIPTION', 'GS_DASH_5', 'GS_DASH_5_DESCRIPTION', 'GS_DASH_6', 'GS_DASH_6_DESCRIPTION', 'GS_DASH_7', 'GS_DASH_7_DESCRIPTION', 'GS_DASH_8', 'GS_DASH_8_DESCRIPTION', 'GS_DASH_9', 'GS_DASH_9_DESCRIPTION', 'PLATINUM_DEPT', 'EXCLUDE_PDF_BKP', 'GS_ADV_CRD_GROC_RPK_CAYU_PCT', 'GS_ADV_CRD_MEAT_BULK_PCT', 'GS_ADV_CRD_CORDER_REPACK_PCT', 'GS_ADV_CRD_FROZEN_PCT', 'GS_ADV_CRD_BAKERY_PCT', 'GS_ADV_CRD_REFRIG_PCT', 'GS_ADV_CRD_ICREAM_PCT', 'GS_SALESMAN_NBR', 'GS_SALESMAN_NAME', 'GS_CM_DROP_SHIP_FLAG', 'GS_CM_PAYMENT_METHOD', 'GS_SELECTION_SERVICE_FEE_FLAG', 'GS_FRZ_RBT_FLAG', 'GS_STMT_FROZ_ADJ_FACTOR', 'GS_STMT_MEAT_ADJ_FACTOR', 'GS_STMT_GROC_ADJ_FACTOR', 'GS_NOTE_PAYOFF_CREDIT_RATE', 'GS_SALES_ADJ_REBATE_RATE', 'GS_TRANSFER_BAL_DASH_NBR', 'GS_CUST_CROSS_REF_DASH_NBR', 'GS_REBATE_CHECK', 'GS_GROUP_CODE_DESC', 'GS_PORTAL_FOLDER_NBR', 'STORE_FAX_NBR', 'GS_AUD_GROUP', 'CREDIT_LIMIT', 'GS_MAP_CD', 'GS_MAP_CD_LTR', 'GS_VENDOR_PACK_IND', 'GS_AD_GROUP', 'GS_TPR_GROUP', 'GS_GBY_GROUP', 'GS_PRICING_ZONE', 'GS_SUPER_SERVE', 'GS_NABISCO', 'GS_WILL_CALL', 'SWELL', 'HQ_FLAG', 'GS_PRIMARY_SHIP_FLAG', 'GS_FUEL_ZONE', 'GS_FUEL_ZONE_DESC', 'GS_AD_GROUP_DESC', 'GS_PRICING_ZONE_DESC']
Data Types: [<cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_CHAR>, <cx_Oracle.DbType DB_TYPE_CHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_DATE>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_NUMBER>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>, <cx_Oracle.DbType DB_TYPE_VARCHAR>]

In [20]:
# Example: Iterate over columns and perform some operation
for column_name, data_type in zip(column_names, data_types):
    # Your logic here
    print(f"Column Name: {column_name}, Data Type: {data_type}")

Column Name: PARTY_SITE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_STATUS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_BILL_TO_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_CHAR>
Column Name: STORE_SHIP_TO_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_CHAR>
Column Name: ACCT_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: ACCT_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ACCT_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ACCT_STATUS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ACCT_CUST_CLASS_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ACCT_CREATION_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: CHAIN_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: CHAIN_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CHAIN_SHORT_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CHAIN_INACTIVE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: START_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STRT_CUST_NBR2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: END_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: END_CUST_NBR2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PRIVATE_LABEL_OFFSET, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SUB_AUTH_OFFST, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AD_START_DAY_OF_WEEK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: COMPANY_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: HQ_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: DIVISION_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: DIVISION_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: EBS_GL_CUST_GROUP_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: EBS_GL_CUST_GROUP_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_GROUP_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_GROUP_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GROUP_BUY_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: STORE_CREATION_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: STORE_INACTIVE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: STORE_LAST_UPDATE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: LOCATION_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: STORE_ADDRESS1, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_ADDRESS2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_ADDRESS3, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_ADDRESS4, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_CITY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_POSTAL_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_STATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_PROVINCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_COUNTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_COUNTRY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_TELEPHONE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CUST_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CUST_ACCT_PROFILE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: PAY_TERMS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PAY_TERM_DESC, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PAY_TERM_START_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: PAY_TERM_END_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: COLLECTOR_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_CYCLE_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ALT_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BASE_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CUST_STATEMENT_FORMAT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PACA_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: TOBACCO_BILLABLE_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: TOBACCO_REBATE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: ZONE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: MILITARY_DODAAC, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SALES_REPRESENTATIVE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BILL_TO_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BILL_TO_STORE_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PRIMARY_CONTACT_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PRIMARY_CONTACT_PHONE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PRIMARY_CONTACT_EMAIL_ADDR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CUSTOMER_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: FINANCE_CHARGES, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: INTEREST_RATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PAYMENT_GRACE_DAYS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: INTEREST_PERIOD_DAYS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_ADDRESS1, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_CITY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_STATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_ZIP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: FINANCE_CHARGE_EFFECTIVE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SUMMARY_STMT_FORMAT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: DELINQUENT_START_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AR_SEGMENT_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AR_GROUP_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: IMPORTED_SOURCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: REMITTANCE_ADDR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_TOLRNCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: INVOICE_TOLRNCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SALES_REP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RISK_TIER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_RETAIL_ACCTNG_REPORT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_LEVEL, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RELATED_CUST_LOCKBOX_APPLLY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SEND_ACH_NOTIFTN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STOCK_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: MULTI_STORE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: EFT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PICKUP_DAY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PAY_DUE_DAY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CREDIT_HOLD, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PAYMENT_TERMS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CREDIT_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BLANK_CHECK_CUSTOMER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AD_PLAN_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_PARTY_SITE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_MULTI_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PATRONAGE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PRINT_STATEMENTS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STATEMENT_INSTRUCTIONS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SEND_TO_AWI_CDH_FLG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_BILLING_CYCLE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_TERMS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_NP_XFER_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_PRINT_STMT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_RET_ACCT_STMT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_STMT_COPIES, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_GROUP_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_PAYMENT_METHOD, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_STMT_LABELS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_PAYMENT_DUE_DAYS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_SUB_STORE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CM_CUST_XREF_NO, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STMT_ADJ_GROUP_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PSUEDOEPHEDRINE_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CALL_FOR_CUSTOMER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CIGARETTE_LICENSE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SMALL_PACK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CIGARETTE_VALIDATION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_CDH_CUSTOMER_CLASS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GAS_REWARDS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: MILES, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: PRINT_STMTS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_CDH_RACK_SERVICE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RETAIL_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: TAX_EXEMPT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ADV_FLAG_7, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: ADV_FLAG6, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BB_AD_PLAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AD_COMMENTS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ADV_FLAG5, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CONFO_AD_PLAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: DEFAULT_TRIP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CATALOG10, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_PRINT_BULLETIN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_SIGN_KIT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SURVEYS, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: ADV_FLAG8, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_AD_OFFSET, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: AGNE_CUSTOMER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CONFO, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: HBA_GM_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: HBA_GM_DISC_OVERIDE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: HBA_GM_DISC, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: ITEM_ALLOWANCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: COD, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SERV_CHARGE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: SINGLE_PICK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AWI_CUSTOMER_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: MULTI_STORE_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: EIGHT_WEEK_BB, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BB_MOD_PROGRAM, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: KPC_END, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: KPC_RETAIL_ZONE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: KPC_START, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
Column Name: AWI_PRODUCT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SPECIALTY_FOODS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: D_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: D_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: D_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: D_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: D_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: D_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SY_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SY_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: SY_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SY_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SY_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SY_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: M_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: M_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: M_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: M_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: M_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: M_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: P_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: P_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: P_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: P_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: P_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: P_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GM_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GM_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: GM_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GM_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GM_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GM_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: C_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: C_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: C_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: C_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: C_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: C_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: F_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: F_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: F_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: F_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: F_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: F_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RG_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RG_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: RG_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RG_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RG_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RG_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: DSD_VENDOR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: CUST_CODE_XREF, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SITE_PICK_SLIP_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SITE_PICK_SLIP_REQ_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: SITE_RANK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ACC_SUBS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: REJ_REASON, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: MAX_VOL_PALL, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ITEM_PAL_ROUND, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: LOG_ORD_QTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: MIN_ORD_QTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ENFORCE_DEPT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: MAX_ORD_QTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PO_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: PO_REQ_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RET_PRC_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RET_PRC_REQ_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CUST_XREF, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: CUST_XREF_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: LEGACY_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: LEGACY_COMPANY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: BILL_TO_SITE_USE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: SHIP_TO_SITE_USE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: HOSTING_DEPT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: RETAILER_DEPT, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: CONTACT_INFO, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_MANAGER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_OWNER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: STORE_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: ACCEPT_SUBS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: INT_PO_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: DIVISION_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: REGION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: DELEGATE_AUTRIZTN_FLG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: AISLE_LIMIT, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
Column Name: ACCT_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: OLD_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_0, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_0_DESCRIPTION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_1, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_1_DESCRIPTION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_2_DESCRIPTION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_3, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_3_DESCRIPTION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_4, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_4_DESCRIPTION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_5, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_5_DESCRIPTION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
Column Name: GS_DASH_6, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>

In [21]:
# Example: Iterate over columns and perform some operation
for i, (column_name, data_type) in enumerate(zip(column_names, data_types), start=1):
    # Your logic here
    print(f"{i} Column Name: {column_name}, Data Type: {data_type}")

1 Column Name: PARTY_SITE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
2 Column Name: STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
3 Column Name: STORE_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
4 Column Name: STORE_STATUS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
5 Column Name: STORE_BILL_TO_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_CHAR>
6 Column Name: STORE_SHIP_TO_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_CHAR>
7 Column Name: ACCT_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
8 Column Name: ACCT_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
9 Column Name: ACCT_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
10 Column Name: ACCT_STATUS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
11 Column Name: ACCT_CUST_CLASS_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
12 Column Name: ACCT_CREATION_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
13 Column Name: CHAIN_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
14 Column Name: CHAIN_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
15 Column Name: CHAIN_SHORT_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
16 Column Name: CHAIN_INACTIVE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
17 Column Name: START_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
18 Column Name: STRT_CUST_NBR2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
19 Column Name: END_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
20 Column Name: END_CUST_NBR2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
21 Column Name: PRIVATE_LABEL_OFFSET, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
22 Column Name: SUB_AUTH_OFFST, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
23 Column Name: AD_START_DAY_OF_WEEK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
24 Column Name: COMPANY_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
25 Column Name: HQ_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
26 Column Name: DIVISION_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
27 Column Name: DIVISION_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
28 Column Name: EBS_GL_CUST_GROUP_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
29 Column Name: EBS_GL_CUST_GROUP_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
30 Column Name: STORE_GROUP_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
31 Column Name: STORE_GROUP_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
32 Column Name: GROUP_BUY_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
33 Column Name: STORE_CREATION_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
34 Column Name: STORE_INACTIVE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
35 Column Name: STORE_LAST_UPDATE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
36 Column Name: LOCATION_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
37 Column Name: STORE_ADDRESS1, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
38 Column Name: STORE_ADDRESS2, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
39 Column Name: STORE_ADDRESS3, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
40 Column Name: STORE_ADDRESS4, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
41 Column Name: STORE_CITY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
42 Column Name: STORE_POSTAL_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
43 Column Name: STORE_STATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
44 Column Name: STORE_PROVINCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
45 Column Name: STORE_COUNTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
46 Column Name: STORE_COUNTRY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
47 Column Name: STORE_TELEPHONE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
48 Column Name: CUST_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
49 Column Name: CUST_ACCT_PROFILE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
50 Column Name: PAY_TERMS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
51 Column Name: PAY_TERM_DESC, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
52 Column Name: PAY_TERM_START_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
53 Column Name: PAY_TERM_END_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
54 Column Name: COLLECTOR_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
55 Column Name: STATEMENT_CYCLE_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
56 Column Name: ALT_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
57 Column Name: BASE_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
58 Column Name: CUST_STATEMENT_FORMAT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
59 Column Name: PACA_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
60 Column Name: TOBACCO_BILLABLE_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
61 Column Name: TOBACCO_REBATE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
62 Column Name: ZONE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
63 Column Name: MILITARY_DODAAC, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
64 Column Name: SALES_REPRESENTATIVE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
65 Column Name: BILL_TO_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
66 Column Name: BILL_TO_STORE_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
67 Column Name: PRIMARY_CONTACT_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
68 Column Name: PRIMARY_CONTACT_PHONE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
69 Column Name: PRIMARY_CONTACT_EMAIL_ADDR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
70 Column Name: CUSTOMER_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
71 Column Name: STORE_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
72 Column Name: FINANCE_CHARGES, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
73 Column Name: INTEREST_RATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
74 Column Name: PAYMENT_GRACE_DAYS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
75 Column Name: INTEREST_PERIOD_DAYS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
76 Column Name: STATEMENT_ADDRESS1, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
77 Column Name: STATEMENT_CITY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
78 Column Name: STATEMENT_STATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
79 Column Name: STATEMENT_ZIP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
80 Column Name: FINANCE_CHARGE_EFFECTIVE_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
81 Column Name: SUMMARY_STMT_FORMAT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
82 Column Name: DELINQUENT_START_DATE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
83 Column Name: AR_SEGMENT_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
84 Column Name: AR_GROUP_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
85 Column Name: IMPORTED_SOURCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
86 Column Name: REMITTANCE_ADDR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
87 Column Name: STATEMENT_TOLRNCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
88 Column Name: INVOICE_TOLRNCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
89 Column Name: SALES_REP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
90 Column Name: RISK_TIER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
91 Column Name: GS_RETAIL_ACCTNG_REPORT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
92 Column Name: STATEMENT_LEVEL, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
93 Column Name: RELATED_CUST_LOCKBOX_APPLLY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
94 Column Name: SEND_ACH_NOTIFTN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
95 Column Name: STOCK_NAME, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
96 Column Name: MULTI_STORE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
97 Column Name: EFT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
98 Column Name: PICKUP_DAY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
99 Column Name: PAY_DUE_DAY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
100 Column Name: CREDIT_HOLD, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
101 Column Name: PAYMENT_TERMS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
102 Column Name: CREDIT_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
103 Column Name: BLANK_CHECK_CUSTOMER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
104 Column Name: AD_PLAN_GROUP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
105 Column Name: AWI_PARTY_SITE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
106 Column Name: AWI_MULTI_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
107 Column Name: PATRONAGE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
108 Column Name: PRINT_STATEMENTS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
109 Column Name: STATEMENT_INSTRUCTIONS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
110 Column Name: SEND_TO_AWI_CDH_FLG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
111 Column Name: CM_BILLING_CYCLE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
112 Column Name: CM_TERMS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
113 Column Name: CM_NP_XFER_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
114 Column Name: CM_PRINT_STMT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
115 Column Name: CM_RET_ACCT_STMT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
116 Column Name: CM_STMT_COPIES, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
117 Column Name: CM_GROUP_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
118 Column Name: CM_PAYMENT_METHOD, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
119 Column Name: CM_STMT_LABELS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
120 Column Name: CM_PAYMENT_DUE_DAYS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
121 Column Name: CM_SUB_STORE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
122 Column Name: CM_CUST_XREF_NO, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
123 Column Name: STMT_ADJ_GROUP_CODE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
124 Column Name: PSUEDOEPHEDRINE_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
125 Column Name: CALL_FOR_CUSTOMER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
126 Column Name: CIGARETTE_LICENSE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
127 Column Name: SMALL_PACK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
128 Column Name: CIGARETTE_VALIDATION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
129 Column Name: AWI_CDH_CUSTOMER_CLASS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
130 Column Name: GAS_REWARDS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
131 Column Name: MILES, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
132 Column Name: PRINT_STMTS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
133 Column Name: AWI_CDH_RACK_SERVICE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
134 Column Name: RETAIL_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
135 Column Name: TAX_EXEMPT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
136 Column Name: ADV_FLAG_7, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
137 Column Name: ADV_FLAG6, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
138 Column Name: BB_AD_PLAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
139 Column Name: AD_COMMENTS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
140 Column Name: ADV_FLAG5, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
141 Column Name: CONFO_AD_PLAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
142 Column Name: DEFAULT_TRIP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
143 Column Name: CATALOG10, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
144 Column Name: AWI_PRINT_BULLETIN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
145 Column Name: AWI_SIGN_KIT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
146 Column Name: SURVEYS, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
147 Column Name: ADV_FLAG8, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
148 Column Name: AWI_AD_OFFSET, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
149 Column Name: AGNE_CUSTOMER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
150 Column Name: CONFO, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
151 Column Name: HBA_GM_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
152 Column Name: HBA_GM_DISC_OVERIDE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
153 Column Name: HBA_GM_DISC, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
154 Column Name: ITEM_ALLOWANCE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
155 Column Name: COD, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
156 Column Name: SERV_CHARGE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
157 Column Name: SINGLE_PICK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
158 Column Name: AWI_CUSTOMER_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
159 Column Name: MULTI_STORE_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
160 Column Name: EIGHT_WEEK_BB, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
161 Column Name: BB_MOD_PROGRAM, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
162 Column Name: KPC_END, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
163 Column Name: KPC_RETAIL_ZONE, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
164 Column Name: KPC_START, Data Type: <cx_Oracle.DbType DB_TYPE_DATE>
165 Column Name: AWI_PRODUCT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
166 Column Name: SPECIALTY_FOODS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
167 Column Name: D_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
168 Column Name: D_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
169 Column Name: D_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
170 Column Name: D_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
171 Column Name: D_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
172 Column Name: D_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
173 Column Name: SY_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
174 Column Name: SY_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
175 Column Name: SY_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
176 Column Name: SY_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
177 Column Name: SY_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
178 Column Name: SY_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
179 Column Name: M_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
180 Column Name: M_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
181 Column Name: M_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
182 Column Name: M_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
183 Column Name: M_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
184 Column Name: M_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
185 Column Name: P_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
186 Column Name: P_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
187 Column Name: P_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
188 Column Name: P_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
189 Column Name: P_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
190 Column Name: P_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
191 Column Name: GM_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
192 Column Name: GM_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
193 Column Name: GM_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
194 Column Name: GM_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
195 Column Name: GM_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
196 Column Name: GM_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
197 Column Name: C_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
198 Column Name: C_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
199 Column Name: C_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
200 Column Name: C_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
201 Column Name: C_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
202 Column Name: C_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
203 Column Name: F_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
204 Column Name: F_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
205 Column Name: F_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
206 Column Name: F_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
207 Column Name: F_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
208 Column Name: F_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
209 Column Name: RG_COST_PLUS_BRACKET_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
210 Column Name: RG_COST_PLUS_BRACKET_NUMBER, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
211 Column Name: RG_MERCHANDISER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
212 Column Name: RG_PRICING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
213 Column Name: RG_SALESMAN, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
214 Column Name: RG_SKID_ROUNDING_FLAG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
215 Column Name: DSD_VENDOR, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
216 Column Name: CUST_CODE_XREF, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
217 Column Name: SITE_PICK_SLIP_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
218 Column Name: SITE_PICK_SLIP_REQ_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
219 Column Name: SITE_RANK, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
220 Column Name: ACC_SUBS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
221 Column Name: REJ_REASON, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
222 Column Name: MAX_VOL_PALL, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
223 Column Name: ITEM_PAL_ROUND, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
224 Column Name: LOG_ORD_QTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
225 Column Name: MIN_ORD_QTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
226 Column Name: ENFORCE_DEPT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
227 Column Name: MAX_ORD_QTY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
228 Column Name: PO_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
229 Column Name: PO_REQ_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
230 Column Name: RET_PRC_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
231 Column Name: RET_PRC_REQ_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
232 Column Name: CUST_XREF, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
233 Column Name: CUST_XREF_DISP, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
234 Column Name: LEGACY_CUST_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
235 Column Name: LEGACY_COMPANY, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
236 Column Name: BILL_TO_SITE_USE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
237 Column Name: SHIP_TO_SITE_USE_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
238 Column Name: HOSTING_DEPT, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
239 Column Name: RETAILER_DEPT, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
240 Column Name: CONTACT_INFO, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
241 Column Name: STORE_MANAGER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
242 Column Name: STORE_OWNER, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
243 Column Name: STORE_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
244 Column Name: ACCEPT_SUBS, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
245 Column Name: INT_PO_REQ, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
246 Column Name: DIVISION_ID, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
247 Column Name: REGION, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
248 Column Name: DELEGATE_AUTRIZTN_FLG, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
249 Column Name: AISLE_LIMIT, Data Type: <cx_Oracle.DbType DB_TYPE_NUMBER>
250 Column Name: ACCT_TYPE, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
251 Column Name: OLD_STORE_NBR, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>
252 Column Name: GS_DASH_0, Data Type: <cx_Oracle.DbType DB_TYPE_VARCHAR>

In [30]:
# Assuming you have a DataFrame named cust_df
column_names_only = cust_df.columns.get_level_values('ColumnName').tolist()

# Display the list of column names
print(len(column_names_only),column_names_only)

316 ['PARTY_SITE_ID', 'STORE_NBR', 'STORE_NAME', 'STORE_STATUS', 'STORE_BILL_TO_FLAG', 'STORE_SHIP_TO_FLAG', 'ACCT_ID', 'ACCT_NBR', 'ACCT_NAME', 'ACCT_STATUS', 'ACCT_CUST_CLASS_CODE', 'ACCT_CREATION_DATE', 'CHAIN_NBR', 'CHAIN_NAME', 'CHAIN_SHORT_NAME', 'CHAIN_INACTIVE_DATE', 'START_CUST_NBR', 'STRT_CUST_NBR2', 'END_CUST_NBR', 'END_CUST_NBR2', 'PRIVATE_LABEL_OFFSET', 'SUB_AUTH_OFFST', 'AD_START_DAY_OF_WEEK', 'COMPANY_CODE', 'HQ_CUST_NBR', 'DIVISION_NBR', 'DIVISION_NAME', 'EBS_GL_CUST_GROUP_NBR', 'EBS_GL_CUST_GROUP_NAME', 'STORE_GROUP_NBR', 'STORE_GROUP_NAME', 'GROUP_BUY_NBR', 'STORE_CREATION_DATE', 'STORE_INACTIVE_DATE', 'STORE_LAST_UPDATE_DATE', 'LOCATION_ID', 'STORE_ADDRESS1', 'STORE_ADDRESS2', 'STORE_ADDRESS3', 'STORE_ADDRESS4', 'STORE_CITY', 'STORE_POSTAL_CODE', 'STORE_STATE', 'STORE_PROVINCE', 'STORE_COUNTY', 'STORE_COUNTRY', 'STORE_TELEPHONE_NBR', 'CUST_STORE_NBR', 'CUST_ACCT_PROFILE_ID', 'PAY_TERMS', 'PAY_TERM_DESC', 'PAY_TERM_START_DATE', 'PAY_TERM_END_DATE', 'COLLECTOR_NAME', 'STATEMENT_CYCLE_NAME', 'ALT_CUST_NBR', 'BASE_CUST_NBR', 'CUST_STATEMENT_FORMAT', 'PACA_FLAG', 'TOBACCO_BILLABLE_FLAG', 'TOBACCO_REBATE', 'ZONE_NBR', 'MILITARY_DODAAC', 'SALES_REPRESENTATIVE', 'BILL_TO_STORE_NBR', 'BILL_TO_STORE_NAME', 'PRIMARY_CONTACT_NAME', 'PRIMARY_CONTACT_PHONE_NBR', 'PRIMARY_CONTACT_EMAIL_ADDR', 'CUSTOMER_GROUP', 'STORE_GROUP', 'FINANCE_CHARGES', 'INTEREST_RATE', 'PAYMENT_GRACE_DAYS', 'INTEREST_PERIOD_DAYS', 'STATEMENT_ADDRESS1', 'STATEMENT_CITY', 'STATEMENT_STATE', 'STATEMENT_ZIP', 'FINANCE_CHARGE_EFFECTIVE_DATE', 'SUMMARY_STMT_FORMAT', 'DELINQUENT_START_DATE', 'AR_SEGMENT_GROUP', 'AR_GROUP_NAME', 'IMPORTED_SOURCE', 'REMITTANCE_ADDR', 'STATEMENT_TOLRNCE', 'INVOICE_TOLRNCE', 'SALES_REP', 'RISK_TIER', 'GS_RETAIL_ACCTNG_REPORT', 'STATEMENT_LEVEL', 'RELATED_CUST_LOCKBOX_APPLLY', 'SEND_ACH_NOTIFTN', 'STOCK_NAME', 'MULTI_STORE', 'EFT', 'PICKUP_DAY', 'PAY_DUE_DAY', 'CREDIT_HOLD', 'PAYMENT_TERMS', 'CREDIT_GROUP', 'BLANK_CHECK_CUSTOMER', 'AD_PLAN_GROUP', 'AWI_PARTY_SITE_ID', 'AWI_MULTI_STORE_NBR', 'PATRONAGE_NBR', 'PRINT_STATEMENTS', 'STATEMENT_INSTRUCTIONS', 'SEND_TO_AWI_CDH_FLG', 'CM_BILLING_CYCLE', 'CM_TERMS', 'CM_NP_XFER_FLAG', 'CM_PRINT_STMT', 'CM_RET_ACCT_STMT', 'CM_STMT_COPIES', 'CM_GROUP_CODE', 'CM_PAYMENT_METHOD', 'CM_STMT_LABELS', 'CM_PAYMENT_DUE_DAYS', 'CM_SUB_STORE', 'CM_CUST_XREF_NO', 'STMT_ADJ_GROUP_CODE', 'PSUEDOEPHEDRINE_FLAG', 'CALL_FOR_CUSTOMER', 'CIGARETTE_LICENSE', 'SMALL_PACK', 'CIGARETTE_VALIDATION', 'AWI_CDH_CUSTOMER_CLASS', 'GAS_REWARDS', 'MILES', 'PRINT_STMTS', 'AWI_CDH_RACK_SERVICE', 'RETAIL_TYPE', 'TAX_EXEMPT', 'ADV_FLAG_7', 'ADV_FLAG6', 'BB_AD_PLAN', 'AD_COMMENTS', 'ADV_FLAG5', 'CONFO_AD_PLAN', 'DEFAULT_TRIP', 'CATALOG10', 'AWI_PRINT_BULLETIN', 'AWI_SIGN_KIT', 'SURVEYS', 'ADV_FLAG8', 'AWI_AD_OFFSET', 'AGNE_CUSTOMER', 'CONFO', 'HBA_GM_FLAG', 'HBA_GM_DISC_OVERIDE', 'HBA_GM_DISC', 'ITEM_ALLOWANCE', 'COD', 'SERV_CHARGE', 'SINGLE_PICK', 'AWI_CUSTOMER_TYPE', 'MULTI_STORE_NUMBER', 'EIGHT_WEEK_BB', 'BB_MOD_PROGRAM', 'KPC_END', 'KPC_RETAIL_ZONE', 'KPC_START', 'AWI_PRODUCT', 'SPECIALTY_FOODS', 'D_COST_PLUS_BRACKET_FLAG', 'D_COST_PLUS_BRACKET_NUMBER', 'D_MERCHANDISER', 'D_PRICING_FLAG', 'D_SALESMAN', 'D_SKID_ROUNDING_FLAG', 'SY_COST_PLUS_BRACKET_FLAG', 'SY_COST_PLUS_BRACKET_NUMBER', 'SY_MERCHANDISER', 'SY_PRICING_FLAG', 'SY_SALESMAN', 'SY_SKID_ROUNDING_FLAG', 'M_COST_PLUS_BRACKET_FLAG', 'M_COST_PLUS_BRACKET_NUMBER', 'M_MERCHANDISER', 'M_PRICING_FLAG', 'M_SALESMAN', 'M_SKID_ROUNDING_FLAG', 'P_COST_PLUS_BRACKET_FLAG', 'P_COST_PLUS_BRACKET_NUMBER', 'P_MERCHANDISER', 'P_PRICING_FLAG', 'P_SALESMAN', 'P_SKID_ROUNDING_FLAG', 'GM_COST_PLUS_BRACKET_FLAG', 'GM_COST_PLUS_BRACKET_NUMBER', 'GM_MERCHANDISER', 'GM_PRICING_FLAG', 'GM_SALESMAN', 'GM_SKID_ROUNDING_FLAG', 'C_COST_PLUS_BRACKET_FLAG', 'C_COST_PLUS_BRACKET_NUMBER', 'C_MERCHANDISER', 'C_PRICING_FLAG', 'C_SALESMAN', 'C_SKID_ROUNDING_FLAG', 'F_COST_PLUS_BRACKET_FLAG', 'F_COST_PLUS_BRACKET_NUMBER', 'F_MERCHANDISER', 'F_PRICING_FLAG', 'F_SALESMAN', 'F_SKID_ROUNDING_FLAG', 'RG_COST_PLUS_BRACKET_FLAG', 'RG_COST_PLUS_BRACKET_NUMBER', 'RG_MERCHANDISER', 'RG_PRICING_FLAG', 'RG_SALESMAN', 'RG_SKID_ROUNDING_FLAG', 'DSD_VENDOR', 'CUST_CODE_XREF', 'SITE_PICK_SLIP_REQ', 'SITE_PICK_SLIP_REQ_DISP', 'SITE_RANK', 'ACC_SUBS', 'REJ_REASON', 'MAX_VOL_PALL', 'ITEM_PAL_ROUND', 'LOG_ORD_QTY', 'MIN_ORD_QTY', 'ENFORCE_DEPT', 'MAX_ORD_QTY', 'PO_REQ', 'PO_REQ_DISP', 'RET_PRC_REQ', 'RET_PRC_REQ_DISP', 'CUST_XREF', 'CUST_XREF_DISP', 'LEGACY_CUST_NBR', 'LEGACY_COMPANY', 'BILL_TO_SITE_USE_ID', 'SHIP_TO_SITE_USE_ID', 'HOSTING_DEPT', 'RETAILER_DEPT', 'CONTACT_INFO', 'STORE_MANAGER', 'STORE_OWNER', 'STORE_TYPE', 'ACCEPT_SUBS', 'INT_PO_REQ', 'DIVISION_ID', 'REGION', 'DELEGATE_AUTRIZTN_FLG', 'AISLE_LIMIT', 'ACCT_TYPE', 'OLD_STORE_NBR', 'GS_DASH_0', 'GS_DASH_0_DESCRIPTION', 'GS_DASH_1', 'GS_DASH_1_DESCRIPTION', 'GS_DASH_2', 'GS_DASH_2_DESCRIPTION', 'GS_DASH_3', 'GS_DASH_3_DESCRIPTION', 'GS_DASH_4', 'GS_DASH_4_DESCRIPTION', 'GS_DASH_5', 'GS_DASH_5_DESCRIPTION', 'GS_DASH_6', 'GS_DASH_6_DESCRIPTION', 'GS_DASH_7', 'GS_DASH_7_DESCRIPTION', 'GS_DASH_8', 'GS_DASH_8_DESCRIPTION', 'GS_DASH_9', 'GS_DASH_9_DESCRIPTION', 'PLATINUM_DEPT', 'EXCLUDE_PDF_BKP', 'GS_ADV_CRD_GROC_RPK_CAYU_PCT', 'GS_ADV_CRD_MEAT_BULK_PCT', 'GS_ADV_CRD_CORDER_REPACK_PCT', 'GS_ADV_CRD_FROZEN_PCT', 'GS_ADV_CRD_BAKERY_PCT', 'GS_ADV_CRD_REFRIG_PCT', 'GS_ADV_CRD_ICREAM_PCT', 'GS_SALESMAN_NBR', 'GS_SALESMAN_NAME', 'GS_CM_DROP_SHIP_FLAG', 'GS_CM_PAYMENT_METHOD', 'GS_SELECTION_SERVICE_FEE_FLAG', 'GS_FRZ_RBT_FLAG', 'GS_STMT_FROZ_ADJ_FACTOR', 'GS_STMT_MEAT_ADJ_FACTOR', 'GS_STMT_GROC_ADJ_FACTOR', 'GS_NOTE_PAYOFF_CREDIT_RATE', 'GS_SALES_ADJ_REBATE_RATE', 'GS_TRANSFER_BAL_DASH_NBR', 'GS_CUST_CROSS_REF_DASH_NBR', 'GS_REBATE_CHECK', 'GS_GROUP_CODE_DESC', 'GS_PORTAL_FOLDER_NBR', 'STORE_FAX_NBR', 'GS_AUD_GROUP', 'CREDIT_LIMIT', 'GS_MAP_CD', 'GS_MAP_CD_LTR', 'GS_VENDOR_PACK_IND', 'GS_AD_GROUP', 'GS_TPR_GROUP', 'GS_GBY_GROUP', 'GS_PRICING_ZONE', 'GS_SUPER_SERVE', 'GS_NABISCO', 'GS_WILL_CALL', 'SWELL', 'HQ_FLAG', 'GS_PRIMARY_SHIP_FLAG', 'GS_FUEL_ZONE', 'GS_FUEL_ZONE_DESC', 'GS_AD_GROUP_DESC', 'GS_PRICING_ZONE_DESC']

In [7]:
%%time
# Get all the party_site_ids from the records of cust_df
party_site_ids = cust_df['PARTY_SITE_ID'].tolist()
print('len(party_site_ids) :',len(party_site_ids))
# Define the batch size (e.g., 1000)
batch_size = 1000

# Calculate the number of batches
num_batches = (len(party_site_ids) + batch_size - 1) // batch_size
print(num_batches)
# Assuming you have a database connection and a cursor named 'source_cursor'
# Adjust the SQL query based on your database and table structure
with open('SelectPSCM.sql', 'r') as file:
    query_template = file.read()
query_template = f"SELECT  FROM xxfin.xxar_customer_master WHERE party_site_id IN ({})"

# Create an empty list to store DataFrames from each batch
all_dfs = []

# Iterate through batches
for i in range(num_batches):
    # Get the start and end indices for the current batch
    start_idx = i * batch_size
    end_idx = (i + 1) * batch_size

    # Extract the party_site_ids for the current batch
    current_batch = party_site_ids[start_idx:end_idx]

    # Generate the SQL query for the current batch
    query = query_template.format(','.join(map(str, current_batch)))

    # Execute the query and fetch the results
    source_cursor.execute(query)
    results = source_cursor.fetchall()

    # Create a DataFrame from the results
    columns = [desc[0] for desc in source_cursor.description]
    current_df = pd.DataFrame(results, columns=columns)

    # Append the current DataFrame to the list
    all_dfs.append(current_df)

# Concatenate all DataFrames into a single DataFrame
final_df = pd.concat(all_dfs, ignore_index=True)

# Display the final DataFrame
print(final_df)

# Get the number of rows in the final DataFrame
print(f"Number of rows in the final DataFrame: {final_df.shape[0]}")

len(party_site_ids) : 2397
3
      PARTY_SITE_ID  STORE_NBR                   STORE_NAME STORE_STATUS  \
0             25275      20054    BLACKIE'S FARM FRESH PROD       Active
1            376902      25317           FAIRWAY E-COMMERCE       Active
2            376998      25401       IMPERIAL BAGS PAPER CO       Active
3            376999      25403       N & P FOOD SERVICES IN       Active
4            377000      25415       PLAINFIELD TOB & CANDY       Active
...             ...        ...                          ...          ...
2387        2678359    9854083                FRED'S MARKET       Active
2388        2859183      30115  CEDAR KNOLLS FARMERS MARKET       Active
2389        3040128      30124                       C-TOWN       Active
2390        3048123      30125                TUSCANY FOODS       Active
2391        3460192  999999994               TEST 999999994       Active

     STORE_BILL_TO_FLAG STORE_SHIP_TO_FLAG  ACCT_ID   ACCT_NBR  \
0                     Y                  Y     6638      20054
1                     N                  Y   269082         79
2                     Y                  Y   248132      25401
3                     Y                  Y   278045      25403
4                     Y                  Y   278057      25415
...                 ...                ...      ...        ...
2387                  Y                  Y  1277052    9854083
2388                  Y                  Y  1307120      30115
2389                  Y                  Y  1375051      30124
2390                  Y                  Y  1378051      30125
2391                  Y                  N  1588064  999999994

                        ACCT_NAME ACCT_STATUS  ... GS_SUPER_SERVE GS_NABISCO  \
0       BLACKIE'S FARM FRESH PROD           A  ...           None       None
1                         FAIRWAY           A  ...           None       None
2          IMPERIAL BAGS PAPER CO           A  ...           None       None
3          N & P FOOD SERVICES IN           A  ...           None       None
4          PLAINFIELD TOB & CANDY           A  ...           None       None
...                           ...         ...  ...            ...        ...
2387                FRED'S MARKET           A  ...           None       None
2388  CEDAR KNOLLS FARMERS MARKET           A  ...           None       None
2389                       C-TOWN           A  ...           None       None
2390                TUSCANY FOODS           A  ...           None       None
2391               TEST 999999994           A  ...           None       None

      GS_WILL_CALL SWELL HQ_FLAG GS_PRIMARY_SHIP_FLAG GS_FUEL_ZONE  \
0             None  None    None                 None         None
1             None  None    None                 None         None
2             None  None    None                 None         None
3             None  None    None                 None         None
4             None  None    None                 None         None
...            ...   ...     ...                  ...          ...
2387          None  None    None                 None         None
2388          None  None    None                 None         None
2389          None  None    None                 None         None
2390          None  None    None                 None         None
2391          None  None    None                 None         None

     GS_FUEL_ZONE_DESC GS_AD_GROUP_DESC GS_PRICING_ZONE_DESC
0                 None             None                 None
1                 None             None                 None
2                 None             None                 None
3                 None             None                 None
4                 None             None                 None
...                ...              ...                  ...
2387              None             None                 None
2388              None             None                 None
2389              None             None                 None
2390              None             None                 None
2391              None             None                 None

[2392 rows x 331 columns]
Number of rows in the final DataFrame: 2392

In [11]:
# Identify party_site_ids not in the final DataFrame

missing_party_site_ids = set(party_site_ids) - set(final_df['PARTY_SITE_ID'])
missing_party_site_ids_len = len(set(party_site_ids)) - len(set(final_df['PARTY_SITE_ID']))
print('Missing party_site_ids:', missing_party_site_ids)
print('missing_party_site_ids_len',missing_party_site_ids_len)
print(2397-2392)

Missing party_site_ids: {3470193, 3470194, 3470195, 3470196, 3467192}
missing_party_site_ids_len 5
5

In [15]:
import pandas as pd

# Your comma-separated values as a string
csv_values = "PARTY_SITE_ID, STORE_NBR, STORE_NAME, STORE_STATUS, STORE_BILL_TO_FLAG, STORE_SHIP_TO_FLAG, ACCT_ID, ACCT_NBR, ACCT_NAME, ACCT_STATUS, ACCT_CUST_CLASS_CODE, ACCT_CREATION_DATE, CHAIN_NBR, CHAIN_NAME, CHAIN_SHORT_NAME, CHAIN_INACTIVE_DATE, START_CUST_NBR, STRT_CUST_NBR2, END_CUST_NBR, END_CUST_NBR2, PRIVATE_LABEL_OFFSET, SUB_AUTH_OFFST, AD_START_DAY_OF_WEEK, COMPANY_CODE, HQ_CUST_NBR, DIVISION_NBR, DIVISION_NAME, EBS_GL_CUST_GROUP_NBR, EBS_GL_CUST_GROUP_NAME, STORE_GROUP_NBR, STORE_GROUP_NAME, GROUP_BUY_NBR, STORE_CREATION_DATE, STORE_INACTIVE_DATE, STORE_LAST_UPDATE_DATE, LOCATION_ID, STORE_ADDRESS1, STORE_ADDRESS2, STORE_ADDRESS3, STORE_ADDRESS4, STORE_CITY, STORE_POSTAL_CODE, STORE_STATE, STORE_PROVINCE, STORE_COUNTY, STORE_COUNTRY, STORE_TELEPHONE_NBR, CUST_STORE_NBR, CUST_ACCT_PROFILE_ID, PAY_TERMS, PAY_TERM_DESC, PAY_TERM_START_DATE, PAY_TERM_END_DATE, COLLECTOR_NAME, STATEMENT_CYCLE_NAME, ALT_CUST_NBR, BASE_CUST_NBR, CUST_STATEMENT_FORMAT, PACA_FLAG, TOBACCO_BILLABLE_FLAG, TOBACCO_REBATE, ZONE_NBR, MILITARY_DODAAC, SALES_REPRESENTATIVE, BILL_TO_STORE_NBR, BILL_TO_STORE_NAME, REQUEST_ID, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, PSUEDOEPHEDRINE_FLAG, CALL_FOR_CUSTOMER, CIGARETTE_LICENSE, SMALL_PACK, CIGARETTE_VALIDATION, AWI_CDH_CUSTOMER_CLASS, GAS_REWARDS, MILES, PRINT_STMTS, AWI_CDH_RACK_SERVICE, RETAIL_TYPE, TAX_EXEMPT, ADV_FLAG_7, ADV_FLAG6, BB_AD_PLAN, AD_COMMENTS, ADV_FLAG5, CONFO_AD_PLAN, DEFAULT_TRIP, CATALOG10, AWI_PRINT_BULLETIN, AWI_SIGN_KIT, SURVEYS, ADV_FLAG8, AWI_AD_OFFSET, AGNE_CUSTOMER, CONFO, HBA_GM_FLAG, HBA_GM_DISC_OVERIDE, HBA_GM_DISC, ITEM_ALLOWANCE, COD, SERV_CHARGE, SINGLE_PICK, AWI_CUSTOMER_TYPE, MULTI_STORE_NUMBER, EIGHT_WEEK_BB, BB_MOD_PROGRAM, KPC_END, KPC_RETAIL_ZONE, KPC_START, AWI_PRODUCT, SPECIALTY_FOODS, D_COST_PLUS_BRACKET_FLAG, D_COST_PLUS_BRACKET_NUMBER, D_DEPARTMENT, D_MERCHANDISER, D_PRICING_FLAG, D_SALESMAN, D_SKID_ROUNDING_FLAG, SY_COST_PLUS_BRACKET_FLAG, SY_COST_PLUS_BRACKET_NUMBER, SY_DEPARTMENT, SY_MERCHANDISER, SY_PRICING_FLAG, SY_SALESMAN, SY_SKID_ROUNDING_FLAG, M_COST_PLUS_BRACKET_FLAG, M_COST_PLUS_BRACKET_NUMBER, M_DEPARTMENT, M_MERCHANDISER, M_PRICING_FLAG, M_SALESMAN, M_SKID_ROUNDING_FLAG, P_COST_PLUS_BRACKET_FLAG, P_COST_PLUS_BRACKET_NUMBER, P_DEPARTMENT, P_MERCHANDISER, P_PRICING_FLAG, P_SALESMAN, P_SKID_ROUNDING_FLAG, GM_COST_PLUS_BRACKET_FLAG, GM_COST_PLUS_BRACKET_NUMBER, GM_DEPARTMENT, GM_MERCHANDISER, GM_PRICING_FLAG, GM_SALESMAN, GM_SKID_ROUNDING_FLAG, C_COST_PLUS_BRACKET_FLAG, C_COST_PLUS_BRACKET_NUMBER, C_DEPARTMENT, C_MERCHANDISER, C_PRICING_FLAG, C_SALESMAN, C_SKID_ROUNDING_FLAG, F_COST_PLUS_BRACKET_FLAG, F_COST_PLUS_BRACKET_NUMBER, F_DEPARTMENT, F_MERCHANDISER, F_PRICING_FLAG, F_SALESMAN, F_SKID_ROUNDING_FLAG, RG_COST_PLUS_BRACKET_FLAG, RG_COST_PLUS_BRACKET_NUMBER, RG_DEPARTMENT, RG_MERCHANDISER, RG_PRICING_FLAG, RG_SALESMAN, RG_SKID_ROUNDING_FLAG, DSD_VENDOR, PRIMARY_CONTACT_NAME, PRIMARY_CONTACT_PHONE_NBR, PRIMARY_CONTACT_EMAIL_ADDR, CUSTOMER_GROUP, STORE_GROUP, FINANCE_CHARGES, INTEREST_RATE, PAYMENT_GRACE_DAYS, INTEREST_PERIOD_DAYS, STATEMENT_ADDRESS1, STATEMENT_CITY, STATEMENT_STATE, STATEMENT_ZIP, FINANCE_CHARGE_EFFECTIVE_DATE, SUMMARY_STMT_FORMAT, DELINQUENT_START_DATE, AR_SEGMENT_GROUP, AR_GROUP_NAME, IMPORTED_SOURCE, REMITTANCE_ADDR, STATEMENT_TOLRNCE, INVOICE_TOLRNCE, SALES_REP, RISK_TIER, GS_RETAIL_ACCTNG_REPORT, STATEMENT_LEVEL, RELATED_CUST_LOCKBOX_APPLLY, SEND_ACH_NOTIFTN, STOCK_NAME, MULTI_STORE, EFT, PICKUP_DAY, PAY_DUE_DAY, CREDIT_HOLD, PAYMENT_TERMS, CREDIT_GROUP, BLANK_CHECK_CUSTOMER, AD_PLAN_GROUP, AWI_PARTY_SITE_ID, AWI_MULTI_STORE_NBR, PATRONAGE_NBR, PRINT_STATEMENTS, STATEMENT_INSTRUCTIONS, SEND_TO_AWI_CDH_FLG, CM_BILLING_CYCLE, CM_TERMS, CM_NP_XFER_FLAG, CM_PRINT_STMT, CM_RET_ACCT_STMT, CM_STMT_COPIES, CM_GROUP_CODE, CM_PAYMENT_METHOD, CM_STMT_LABELS, CM_PAYMENT_DUE_DAYS, CM_SUB_STORE, CM_CUST_XREF_NO, STMT_ADJ_GROUP_CODE, CUST_CODE_XREF, SITE_PICK_SLIP_REQ, SITE_PICK_SLIP_REQ_DISP, SITE_RANK, ACC_SUBS, REJ_REASON, MAX_VOL_PALL, ITEM_PAL_ROUND, LOG_ORD_QTY, MIN_ORD_QTY, ENFORCE_DEPT, MAX_ORD_QTY, PO_REQ, PO_REQ_DISP, RET_PRC_REQ, RET_PRC_REQ_DISP, CUST_XREF, CUST_XREF_DISP, LEGACY_CUST_NBR, LEGACY_COMPANY, SHIP_TO_SITE_USE_ID, BILL_TO_SITE_USE_ID, HOSTING_DEPT, RETAILER_DEPT, CONTACT_INFO, STORE_MANAGER, STORE_OWNER, STORE_TYPE, ACCEPT_SUBS, INT_PO_REQ, LAST_BILL_DATE, DIVISION_ID, REGION, DELEGATE_AUTRIZTN_FLG, AISLE_LIMIT, ACCT_TYPE, OLD_STORE_NBR, GS_DASH_0, GS_DASH_0_DESCRIPTION, GS_DASH_1, GS_DASH_1_DESCRIPTION, GS_DASH_2, GS_DASH_2_DESCRIPTION, GS_DASH_3, GS_DASH_3_DESCRIPTION, GS_DASH_4, GS_DASH_4_DESCRIPTION, GS_DASH_5, GS_DASH_5_DESCRIPTION, GS_DASH_6, GS_DASH_6_DESCRIPTION, GS_DASH_7, GS_DASH_7_DESCRIPTION, GS_DASH_8, GS_DASH_8_DESCRIPTION, GS_DASH_9, GS_DASH_9_DESCRIPTION, PLATINUM_DEPT, EXCLUDE_PDF_BKP, GS_ADV_CRD_GROC_RPK_CAYU_PCT, GS_ADV_CRD_MEAT_BULK_PCT, GS_ADV_CRD_CORDER_REPACK_PCT, GS_ADV_CRD_FROZEN_PCT, GS_ADV_CRD_BAKERY_PCT, GS_ADV_CRD_REFRIG_PCT, GS_ADV_CRD_ICREAM_PCT, GS_SALESMAN_NBR, GS_SALESMAN_NAME, GS_CM_DROP_SHIP_FLAG, GS_CM_PAYMENT_METHOD, GS_SELECTION_SERVICE_FEE_FLAG, GS_FRZ_RBT_FLAG, GS_STMT_FROZ_ADJ_FACTOR, GS_STMT_MEAT_ADJ_FACTOR, GS_STMT_GROC_ADJ_FACTOR, GS_NOTE_PAYOFF_CREDIT_RATE, GS_SALES_ADJ_REBATE_RATE, GS_TRANSFER_BAL_DASH_NBR, GS_CUST_CROSS_REF_DASH_NBR, GS_REBATE_CHECK, GS_GROUP_CODE_DESC, GS_PORTAL_FOLDER_NBR, STORE_FAX_NBR, GS_AUD_GROUP, CREDIT_LIMIT, GS_AD_GROUP, GS_TPR_GROUP, GS_GBY_GROUP, GS_PRICING_ZONE, GS_MAP_CD, GS_MAP_CD_LTR, GS_VENDOR_PACK_IND, GS_SUPER_SERVE, GS_NABISCO, GS_WILL_CALL, SWELL, HQ_FLAG, GS_PRIMARY_SHIP_FLAG, GS_FUEL_ZONE, GS_FUEL_ZONE_DESC, GS_AD_GROUP_DESC, GS_PRICING_ZONE_DESC"  # Replace ... with the remaining values

# Split the string into a list of values
values_list = csv_values.split(', ')

# Create a DataFrame with one column containing the values
df = pd.DataFrame({'Columns in CM': values_list})

# Export DataFrame to Excel
df.to_excel('output_file.xlsx', index=False)

In [23]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\user\anaconda3\lib\site-packages (3.0.7)
Requirement already satisfied: et-xmlfile in c:\users\user\anaconda3\lib\site-packages (from openpyxl) (1.0.1)
Note: you may need to restart the kernel to use updated packages.

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
WARNING: There was an error checking the latest version of pip.

In [26]:
# import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
existing_file_path = 'output_file.xlsx'
book = load_workbook(existing_file_path)
writer = pd.ExcelWriter(existing_file_path, engine='openpyxl') 
writer.book = book

# Your comma-separated values as a string
# csv_values = "PARTY_SITE_ID, STORE_NBR, STORE_NAME, ..."  # Replace ... with the remaining values

# Split the string into a list of values
# values_list = csv_values.split(', ')

# Create a DataFrame with one column containing the values
df = pd.DataFrame({'Columns in df': column_names_only})

# Write the DataFrame to the Excel file in the second column
df.to_excel(writer, sheet_name='Sheet1', startcol=1, index=False, header=False)

# Save the changes
writer.save()
writer.close()

In [28]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
existing_file_path = 'output_file.xlsx'
book = load_workbook(existing_file_path)


# Create a DataFrame with one column containing the values
df = pd.DataFrame({'Columns in df': column_names_only})

# Open the existing sheet in the workbook
writer = pd.ExcelWriter(existing_file_path, engine='openpyxl') 
writer.book = book
writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

# Write the DataFrame to the Excel file starting from the second column
start_col = writer.sheets['Sheet1'].max_column + 1 if 'Sheet1' in writer.sheets else 1
df.to_excel(writer, sheet_name='Sheet1', startcol=start_col, index=False, header=False)

# Save the changes
writer.save()
writer.close()

In [32]:

from openpyxl import load_workbook

# Load the existing Excel file
existing_file_path = 'output_file.xlsx'
book = load_workbook(existing_file_path)

# Create a DataFrame with one column containing the values
df = pd.DataFrame({'Columns from df': column_names_only})

# Open the existing sheet in the workbook
writer = pd.ExcelWriter(existing_file_path, engine='openpyxl') 
writer.book = book
writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

# Write the DataFrame to the Excel file starting from the second column
start_col = writer.sheets['Sheet1'].max_column + 1 if 'Sheet1' in writer.sheets else 1
df.to_excel(writer, sheet_name='Sheet1', startcol=start_col, index=False, header=False)

# Save the changes
writer.save()
writer.close()

In [34]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
existing_file_path = 'output_file.xlsx'
book = load_workbook(existing_file_path)

# Your list of column names from cust_df
# column_names_only = ["PARTY_SITE_ID", "STORE_NBR", "STORE_NAME", ...]  # Replace ... with the remaining values

# Create a DataFrame with one column containing the values
df = pd.DataFrame({'Columns from df': column_names_only})

# Open the existing sheet in the workbook
writer = pd.ExcelWriter(existing_file_path, engine='openpyxl') 
writer.book = book
writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

# Check if 'Sheet1' exists in the workbook
if 'Sheet1' in writer.sheets:
    sheet = writer.sheets['Sheet1']

    # Write the header 'Columns from df' in the first row of the second column
    sheet.cell(row=1, column=sheet.max_column + 1, value='Columns from df')

    # Iterate through each column name from the DataFrame
    for i, column_name in enumerate(column_names_only, start=2):
        # Check if the column name is already in the first column
        if column_name in sheet['A']:
            # If found, find the row number and write the column name in the adjacent column
            row_number = sheet['A'].index(column_name) + 1
            sheet.cell(row=row_number, column=sheet.max_column, value=column_name)
        else:
            # If not found, write the column name in the last row of the first column
            sheet.cell(row=sheet.max_row + 1, column=1, value=column_name)

# Save the changes
writer.save()
writer.close()

In [35]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
existing_file_path = 'output_file.xlsx'
book = load_workbook(existing_file_path)

# Your list of column names from cust_df
# column_names_only = ["PARTY_SITE_ID", "STORE_NBR", "STORE_NAME", ...]  # Replace ... with the remaining values

# Open the existing sheet in the workbook
writer = pd.ExcelWriter(existing_file_path, engine='openpyxl') 
writer.book = book
writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

# Check if 'Sheet1' exists in the workbook
if 'Sheet1' in writer.sheets:
    sheet = writer.sheets['Sheet1']

    # Write the header 'Columns from df' in the first row of the second column
    sheet.cell(row=1, column=sheet.max_column + 1, value='Columns from df')

    # Iterate through each column name from the DataFrame
    for i, column_name in enumerate(column_names_only, start=2):
        # Write the column name in the second column
        sheet.cell(row=i, column=sheet.max_column, value=column_name)

# Save the changes
writer.save()
writer.close()

In [45]:
# Given string of column names
Audit_columns = "PARTY_SITE_ID, STORE_NBR, STORE_NAME, STORE_STATUS, STORE_BILL_TO_FLAG, STORE_SHIP_TO_FLAG, ACCT_ID, ACCT_NBR, ACCT_NAME, ACCT_STATUS, ACCT_CUST_CLASS_CODE, ACCT_CREATION_DATE, CHAIN_NBR, CHAIN_NAME, CHAIN_SHORT_NAME, CHAIN_INACTIVE_DATE, START_CUST_NBR, STRT_CUST_NBR2, END_CUST_NBR, END_CUST_NBR2, PRIVATE_LABEL_OFFSET, SUB_AUTH_OFFST, AD_START_DAY_OF_WEEK, COMPANY_CODE, HQ_CUST_NBR, DIVISION_NBR, DIVISION_NAME, EBS_GL_CUST_GROUP_NBR, EBS_GL_CUST_GROUP_NAME, STORE_GROUP_NBR, STORE_GROUP_NAME, GROUP_BUY_NBR, STORE_CREATION_DATE, STORE_INACTIVE_DATE, STORE_LAST_UPDATE_DATE, LOCATION_ID, STORE_ADDRESS1, STORE_ADDRESS2, STORE_ADDRESS3, STORE_ADDRESS4, STORE_CITY, STORE_POSTAL_CODE, STORE_STATE, STORE_PROVINCE, STORE_COUNTY, STORE_COUNTRY, STORE_TELEPHONE_NBR, CUST_STORE_NBR, CUST_ACCT_PROFILE_ID, PAY_TERMS, PAY_TERM_DESC, PAY_TERM_START_DATE, PAY_TERM_END_DATE, COLLECTOR_NAME, STATEMENT_CYCLE_NAME, ALT_CUST_NBR, BASE_CUST_NBR, CUST_STATEMENT_FORMAT, PACA_FLAG, TOBACCO_BILLABLE_FLAG, TOBACCO_REBATE, ZONE_NBR, MILITARY_DODAAC, SALES_REPRESENTATIVE, REQUEST_ID, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, BILL_TO_STORE_NBR, BILL_TO_STORE_NAME, PSUEDOEPHEDRINE_FLAG, CALL_FOR_CUSTOMER, CIGARETTE_LICENSE, SMALL_PACK, CIGARETTE_VALIDATION, AWI_CDH_CUSTOMER_CLASS, GAS_REWARDS, MILES, PRINT_STMTS, AWI_CDH_RACK_SERVICE, RETAIL_TYPE, TAX_EXEMPT, ADV_FLAG_7, ADV_FLAG6, BB_AD_PLAN, AD_COMMENTS, ADV_FLAG5, CONFO_AD_PLAN, DEFAULT_TRIP, CATALOG10, AWI_PRINT_BULLETIN, AWI_SIGN_KIT, SURVEYS, ADV_FLAG8, AWI_AD_OFFSET, AGNE_CUSTOMER, CONFO, HBA_GM_FLAG, HBA_GM_DISC_OVERIDE, HBA_GM_DISC, ITEM_ALLOWANCE, COD, SERV_CHARGE, SINGLE_PICK, AWI_CUSTOMER_TYPE, MULTI_STORE_NUMBER, EIGHT_WEEK_BB, BB_MOD_PROGRAM, KPC_END, KPC_RETAIL_ZONE, KPC_START, AWI_PRODUCT, SPECIALTY_FOODS, D_COST_PLUS_BRACKET_FLAG, D_COST_PLUS_BRACKET_NUMBER, D_DEPARTMENT, D_MERCHANDISER, D_PRICING_FLAG, D_SALESMAN, D_SKID_ROUNDING_FLAG, SY_COST_PLUS_BRACKET_FLAG, SY_COST_PLUS_BRACKET_NUMBER, SY_DEPARTMENT, SY_MERCHANDISER, SY_PRICING_FLAG, SY_SALESMAN, SY_SKID_ROUNDING_FLAG, M_COST_PLUS_BRACKET_FLAG, M_COST_PLUS_BRACKET_NUMBER, M_DEPARTMENT, M_MERCHANDISER, M_PRICING_FLAG, M_SALESMAN, M_SKID_ROUNDING_FLAG, P_COST_PLUS_BRACKET_FLAG, P_COST_PLUS_BRACKET_NUMBER, P_DEPARTMENT, P_MERCHANDISER, P_PRICING_FLAG, P_SALESMAN, P_SKID_ROUNDING_FLAG, GM_COST_PLUS_BRACKET_FLAG, GM_COST_PLUS_BRACKET_NUMBER, GM_DEPARTMENT, GM_MERCHANDISER, GM_PRICING_FLAG, GM_SALESMAN, GM_SKID_ROUNDING_FLAG, C_COST_PLUS_BRACKET_FLAG, C_COST_PLUS_BRACKET_NUMBER, C_DEPARTMENT, C_MERCHANDISER, C_PRICING_FLAG, C_SALESMAN, C_SKID_ROUNDING_FLAG, F_COST_PLUS_BRACKET_FLAG, F_COST_PLUS_BRACKET_NUMBER, F_DEPARTMENT, F_MERCHANDISER, F_PRICING_FLAG, F_SALESMAN, F_SKID_ROUNDING_FLAG, RG_COST_PLUS_BRACKET_FLAG, RG_COST_PLUS_BRACKET_NUMBER, RG_DEPARTMENT, RG_MERCHANDISER, RG_PRICING_FLAG, RG_SALESMAN, RG_SKID_ROUNDING_FLAG, DSD_VENDOR, PRIMARY_CONTACT_NAME, PRIMARY_CONTACT_PHONE_NBR, PRIMARY_CONTACT_EMAIL_ADDR, CUSTOMER_GROUP, STORE_GROUP, FINANCE_CHARGES, INTEREST_RATE, PAYMENT_GRACE_DAYS, INTEREST_PERIOD_DAYS, STATEMENT_ADDRESS1, STATEMENT_CITY, STATEMENT_STATE, STATEMENT_ZIP, FINANCE_CHARGE_EFFECTIVE_DATE, SUMMARY_STMT_FORMAT, DELINQUENT_START_DATE, AR_SEGMENT_GROUP, AR_GROUP_NAME, IMPORTED_SOURCE, REMITTANCE_ADDR, STATEMENT_TOLRNCE, INVOICE_TOLRNCE, SALES_REP, RISK_TIER, GS_RETAIL_ACCTNG_REPORT, STATEMENT_LEVEL, RELATED_CUST_LOCKBOX_APPLLY, SEND_ACH_NOTIFTN, STOCK_NAME, MULTI_STORE, EFT, PICKUP_DAY, PAY_DUE_DAY, CREDIT_HOLD, PAYMENT_TERMS, CREDIT_GROUP, BLANK_CHECK_CUSTOMER, AD_PLAN_GROUP, AWI_PARTY_SITE_ID, AWI_MULTI_STORE_NBR, PATRONAGE_NBR, PRINT_STATEMENTS, STATEMENT_INSTRUCTIONS, SEND_TO_AWI_CDH_FLG, CM_BILLING_CYCLE, CM_TERMS, CM_NP_XFER_FLAG, CM_PRINT_STMT, CM_RET_ACCT_STMT, CM_STMT_COPIES, CM_GROUP_CODE, CM_PAYMENT_METHOD, CM_STMT_LABELS, CM_PAYMENT_DUE_DAYS, CM_SUB_STORE, CM_CUST_XREF_NO, STMT_ADJ_GROUP_CODE, CUST_CODE_XREF, SITE_PICK_SLIP_REQ, SITE_PICK_SLIP_REQ_DISP, SITE_RANK, ACC_SUBS, REJ_REASON, MAX_VOL_PALL, ITEM_PAL_ROUND, LOG_ORD_QTY, MIN_ORD_QTY, ENFORCE_DEPT, MAX_ORD_QTY, PO_REQ, PO_REQ_DISP, RET_PRC_REQ, RET_PRC_REQ_DISP, CUST_XREF, CUST_XREF_DISP, LEGACY_CUST_NBR, LEGACY_COMPANY, SHIP_TO_SITE_USE_ID, BILL_TO_SITE_USE_ID, HOSTING_DEPT, RETAILER_DEPT, CONTACT_INFO, STORE_MANAGER, STORE_OWNER, STORE_TYPE, ACCEPT_SUBS, INT_PO_REQ, LAST_BILL_DATE, DIVISION_ID, REGION, DELEGATE_AUTRIZTN_FLG, AISLE_LIMIT, ACCT_TYPE, OLD_STORE_NBR, GS_DASH_0, GS_DASH_0_DESCRIPTION, GS_DASH_1, GS_DASH_1_DESCRIPTION, GS_DASH_2, GS_DASH_2_DESCRIPTION, GS_DASH_3, GS_DASH_3_DESCRIPTION, GS_DASH_4, GS_DASH_4_DESCRIPTION, GS_DASH_5, GS_DASH_5_DESCRIPTION, GS_DASH_6, GS_DASH_6_DESCRIPTION, GS_DASH_7, GS_DASH_7_DESCRIPTION, GS_DASH_8, GS_DASH_8_DESCRIPTION, GS_DASH_9, GS_DASH_9_DESCRIPTION, PLATINUM_DEPT, EXCLUDE_PDF_BKP, GS_ADV_CRD_GROC_RPK_CAYU_PCT, GS_ADV_CRD_MEAT_BULK_PCT, GS_ADV_CRD_CORDER_REPACK_PCT, GS_ADV_CRD_FROZEN_PCT, GS_ADV_CRD_BAKERY_PCT, GS_ADV_CRD_REFRIG_PCT, GS_ADV_CRD_ICREAM_PCT, GS_SALESMAN_NBR, GS_SALESMAN_NAME, GS_CM_DROP_SHIP_FLAG, GS_CM_PAYMENT_METHOD, GS_SELECTION_SERVICE_FEE_FLAG, GS_FRZ_RBT_FLAG, GS_STMT_FROZ_ADJ_FACTOR, GS_STMT_MEAT_ADJ_FACTOR, GS_STMT_GROC_ADJ_FACTOR, GS_NOTE_PAYOFF_CREDIT_RATE, GS_SALES_ADJ_REBATE_RATE, GS_TRANSFER_BAL_DASH_NBR, GS_CUST_CROSS_REF_DASH_NBR, GS_REBATE_CHECK, GS_GROUP_CODE_DESC, GS_PORTAL_FOLDER_NBR, STORE_FAX_NBR, GS_AUD_GROUP, CREDIT_LIMIT, GS_AD_GROUP, GS_TPR_GROUP, GS_GBY_GROUP, GS_PRICING_ZONE, GS_MAP_CD, GS_MAP_CD_LTR, GS_VENDOR_PACK_IND, GS_SUPER_SERVE, GS_NABISCO, GS_WILL_CALL, SWELL, HQ_FLAG, GS_PRIMARY_SHIP_FLAG, GS_FUEL_ZONE, GS_FUEL_ZONE_DESC, GS_AD_GROUP_DESC, GS_PRICING_ZONE_DESC"
# Split the string into a list of column names
Audit_columns_list = Audit_columns.split(', ')

# Display the list of column names
print(len(Audit_columns_list),Audit_columns_list)

331 ['PARTY_SITE_ID', 'STORE_NBR', 'STORE_NAME', 'STORE_STATUS', 'STORE_BILL_TO_FLAG', 'STORE_SHIP_TO_FLAG', 'ACCT_ID', 'ACCT_NBR', 'ACCT_NAME', 'ACCT_STATUS', 'ACCT_CUST_CLASS_CODE', 'ACCT_CREATION_DATE', 'CHAIN_NBR', 'CHAIN_NAME', 'CHAIN_SHORT_NAME', 'CHAIN_INACTIVE_DATE', 'START_CUST_NBR', 'STRT_CUST_NBR2', 'END_CUST_NBR', 'END_CUST_NBR2', 'PRIVATE_LABEL_OFFSET', 'SUB_AUTH_OFFST', 'AD_START_DAY_OF_WEEK', 'COMPANY_CODE', 'HQ_CUST_NBR', 'DIVISION_NBR', 'DIVISION_NAME', 'EBS_GL_CUST_GROUP_NBR', 'EBS_GL_CUST_GROUP_NAME', 'STORE_GROUP_NBR', 'STORE_GROUP_NAME', 'GROUP_BUY_NBR', 'STORE_CREATION_DATE', 'STORE_INACTIVE_DATE', 'STORE_LAST_UPDATE_DATE', 'LOCATION_ID', 'STORE_ADDRESS1', 'STORE_ADDRESS2', 'STORE_ADDRESS3', 'STORE_ADDRESS4', 'STORE_CITY', 'STORE_POSTAL_CODE', 'STORE_STATE', 'STORE_PROVINCE', 'STORE_COUNTY', 'STORE_COUNTRY', 'STORE_TELEPHONE_NBR', 'CUST_STORE_NBR', 'CUST_ACCT_PROFILE_ID', 'PAY_TERMS', 'PAY_TERM_DESC', 'PAY_TERM_START_DATE', 'PAY_TERM_END_DATE', 'COLLECTOR_NAME', 'STATEMENT_CYCLE_NAME', 'ALT_CUST_NBR', 'BASE_CUST_NBR', 'CUST_STATEMENT_FORMAT', 'PACA_FLAG', 'TOBACCO_BILLABLE_FLAG', 'TOBACCO_REBATE', 'ZONE_NBR', 'MILITARY_DODAAC', 'SALES_REPRESENTATIVE', 'REQUEST_ID', 'CREATION_DATE', 'CREATED_BY', 'LAST_UPDATE_DATE', 'LAST_UPDATED_BY', 'LAST_UPDATE_LOGIN', 'BILL_TO_STORE_NBR', 'BILL_TO_STORE_NAME', 'PSUEDOEPHEDRINE_FLAG', 'CALL_FOR_CUSTOMER', 'CIGARETTE_LICENSE', 'SMALL_PACK', 'CIGARETTE_VALIDATION', 'AWI_CDH_CUSTOMER_CLASS', 'GAS_REWARDS', 'MILES', 'PRINT_STMTS', 'AWI_CDH_RACK_SERVICE', 'RETAIL_TYPE', 'TAX_EXEMPT', 'ADV_FLAG_7', 'ADV_FLAG6', 'BB_AD_PLAN', 'AD_COMMENTS', 'ADV_FLAG5', 'CONFO_AD_PLAN', 'DEFAULT_TRIP', 'CATALOG10', 'AWI_PRINT_BULLETIN', 'AWI_SIGN_KIT', 'SURVEYS', 'ADV_FLAG8', 'AWI_AD_OFFSET', 'AGNE_CUSTOMER', 'CONFO', 'HBA_GM_FLAG', 'HBA_GM_DISC_OVERIDE', 'HBA_GM_DISC', 'ITEM_ALLOWANCE', 'COD', 'SERV_CHARGE', 'SINGLE_PICK', 'AWI_CUSTOMER_TYPE', 'MULTI_STORE_NUMBER', 'EIGHT_WEEK_BB', 'BB_MOD_PROGRAM', 'KPC_END', 'KPC_RETAIL_ZONE', 'KPC_START', 'AWI_PRODUCT', 'SPECIALTY_FOODS', 'D_COST_PLUS_BRACKET_FLAG', 'D_COST_PLUS_BRACKET_NUMBER', 'D_DEPARTMENT', 'D_MERCHANDISER', 'D_PRICING_FLAG', 'D_SALESMAN', 'D_SKID_ROUNDING_FLAG', 'SY_COST_PLUS_BRACKET_FLAG', 'SY_COST_PLUS_BRACKET_NUMBER', 'SY_DEPARTMENT', 'SY_MERCHANDISER', 'SY_PRICING_FLAG', 'SY_SALESMAN', 'SY_SKID_ROUNDING_FLAG', 'M_COST_PLUS_BRACKET_FLAG', 'M_COST_PLUS_BRACKET_NUMBER', 'M_DEPARTMENT', 'M_MERCHANDISER', 'M_PRICING_FLAG', 'M_SALESMAN', 'M_SKID_ROUNDING_FLAG', 'P_COST_PLUS_BRACKET_FLAG', 'P_COST_PLUS_BRACKET_NUMBER', 'P_DEPARTMENT', 'P_MERCHANDISER', 'P_PRICING_FLAG', 'P_SALESMAN', 'P_SKID_ROUNDING_FLAG', 'GM_COST_PLUS_BRACKET_FLAG', 'GM_COST_PLUS_BRACKET_NUMBER', 'GM_DEPARTMENT', 'GM_MERCHANDISER', 'GM_PRICING_FLAG', 'GM_SALESMAN', 'GM_SKID_ROUNDING_FLAG', 'C_COST_PLUS_BRACKET_FLAG', 'C_COST_PLUS_BRACKET_NUMBER', 'C_DEPARTMENT', 'C_MERCHANDISER', 'C_PRICING_FLAG', 'C_SALESMAN', 'C_SKID_ROUNDING_FLAG', 'F_COST_PLUS_BRACKET_FLAG', 'F_COST_PLUS_BRACKET_NUMBER', 'F_DEPARTMENT', 'F_MERCHANDISER', 'F_PRICING_FLAG', 'F_SALESMAN', 'F_SKID_ROUNDING_FLAG', 'RG_COST_PLUS_BRACKET_FLAG', 'RG_COST_PLUS_BRACKET_NUMBER', 'RG_DEPARTMENT', 'RG_MERCHANDISER', 'RG_PRICING_FLAG', 'RG_SALESMAN', 'RG_SKID_ROUNDING_FLAG', 'DSD_VENDOR', 'PRIMARY_CONTACT_NAME', 'PRIMARY_CONTACT_PHONE_NBR', 'PRIMARY_CONTACT_EMAIL_ADDR', 'CUSTOMER_GROUP', 'STORE_GROUP', 'FINANCE_CHARGES', 'INTEREST_RATE', 'PAYMENT_GRACE_DAYS', 'INTEREST_PERIOD_DAYS', 'STATEMENT_ADDRESS1', 'STATEMENT_CITY', 'STATEMENT_STATE', 'STATEMENT_ZIP', 'FINANCE_CHARGE_EFFECTIVE_DATE', 'SUMMARY_STMT_FORMAT', 'DELINQUENT_START_DATE', 'AR_SEGMENT_GROUP', 'AR_GROUP_NAME', 'IMPORTED_SOURCE', 'REMITTANCE_ADDR', 'STATEMENT_TOLRNCE', 'INVOICE_TOLRNCE', 'SALES_REP', 'RISK_TIER', 'GS_RETAIL_ACCTNG_REPORT', 'STATEMENT_LEVEL', 'RELATED_CUST_LOCKBOX_APPLLY', 'SEND_ACH_NOTIFTN', 'STOCK_NAME', 'MULTI_STORE', 'EFT', 'PICKUP_DAY', 'PAY_DUE_DAY', 'CREDIT_HOLD', 'PAYMENT_TERMS', 'CREDIT_GROUP', 'BLANK_CHECK_CUSTOMER', 'AD_PLAN_GROUP', 'AWI_PARTY_SITE_ID', 'AWI_MULTI_STORE_NBR', 'PATRONAGE_NBR', 'PRINT_STATEMENTS', 'STATEMENT_INSTRUCTIONS', 'SEND_TO_AWI_CDH_FLG', 'CM_BILLING_CYCLE', 'CM_TERMS', 'CM_NP_XFER_FLAG', 'CM_PRINT_STMT', 'CM_RET_ACCT_STMT', 'CM_STMT_COPIES', 'CM_GROUP_CODE', 'CM_PAYMENT_METHOD', 'CM_STMT_LABELS', 'CM_PAYMENT_DUE_DAYS', 'CM_SUB_STORE', 'CM_CUST_XREF_NO', 'STMT_ADJ_GROUP_CODE', 'CUST_CODE_XREF', 'SITE_PICK_SLIP_REQ', 'SITE_PICK_SLIP_REQ_DISP', 'SITE_RANK', 'ACC_SUBS', 'REJ_REASON', 'MAX_VOL_PALL', 'ITEM_PAL_ROUND', 'LOG_ORD_QTY', 'MIN_ORD_QTY', 'ENFORCE_DEPT', 'MAX_ORD_QTY', 'PO_REQ', 'PO_REQ_DISP', 'RET_PRC_REQ', 'RET_PRC_REQ_DISP', 'CUST_XREF', 'CUST_XREF_DISP', 'LEGACY_CUST_NBR', 'LEGACY_COMPANY', 'SHIP_TO_SITE_USE_ID', 'BILL_TO_SITE_USE_ID', 'HOSTING_DEPT', 'RETAILER_DEPT', 'CONTACT_INFO', 'STORE_MANAGER', 'STORE_OWNER', 'STORE_TYPE', 'ACCEPT_SUBS', 'INT_PO_REQ', 'LAST_BILL_DATE', 'DIVISION_ID', 'REGION', 'DELEGATE_AUTRIZTN_FLG', 'AISLE_LIMIT', 'ACCT_TYPE', 'OLD_STORE_NBR', 'GS_DASH_0', 'GS_DASH_0_DESCRIPTION', 'GS_DASH_1', 'GS_DASH_1_DESCRIPTION', 'GS_DASH_2', 'GS_DASH_2_DESCRIPTION', 'GS_DASH_3', 'GS_DASH_3_DESCRIPTION', 'GS_DASH_4', 'GS_DASH_4_DESCRIPTION', 'GS_DASH_5', 'GS_DASH_5_DESCRIPTION', 'GS_DASH_6', 'GS_DASH_6_DESCRIPTION', 'GS_DASH_7', 'GS_DASH_7_DESCRIPTION', 'GS_DASH_8', 'GS_DASH_8_DESCRIPTION', 'GS_DASH_9', 'GS_DASH_9_DESCRIPTION', 'PLATINUM_DEPT', 'EXCLUDE_PDF_BKP', 'GS_ADV_CRD_GROC_RPK_CAYU_PCT', 'GS_ADV_CRD_MEAT_BULK_PCT', 'GS_ADV_CRD_CORDER_REPACK_PCT', 'GS_ADV_CRD_FROZEN_PCT', 'GS_ADV_CRD_BAKERY_PCT', 'GS_ADV_CRD_REFRIG_PCT', 'GS_ADV_CRD_ICREAM_PCT', 'GS_SALESMAN_NBR', 'GS_SALESMAN_NAME', 'GS_CM_DROP_SHIP_FLAG', 'GS_CM_PAYMENT_METHOD', 'GS_SELECTION_SERVICE_FEE_FLAG', 'GS_FRZ_RBT_FLAG', 'GS_STMT_FROZ_ADJ_FACTOR', 'GS_STMT_MEAT_ADJ_FACTOR', 'GS_STMT_GROC_ADJ_FACTOR', 'GS_NOTE_PAYOFF_CREDIT_RATE', 'GS_SALES_ADJ_REBATE_RATE', 'GS_TRANSFER_BAL_DASH_NBR', 'GS_CUST_CROSS_REF_DASH_NBR', 'GS_REBATE_CHECK', 'GS_GROUP_CODE_DESC', 'GS_PORTAL_FOLDER_NBR', 'STORE_FAX_NBR', 'GS_AUD_GROUP', 'CREDIT_LIMIT', 'GS_AD_GROUP', 'GS_TPR_GROUP', 'GS_GBY_GROUP', 'GS_PRICING_ZONE', 'GS_MAP_CD', 'GS_MAP_CD_LTR', 'GS_VENDOR_PACK_IND', 'GS_SUPER_SERVE', 'GS_NABISCO', 'GS_WILL_CALL', 'SWELL', 'HQ_FLAG', 'GS_PRIMARY_SHIP_FLAG', 'GS_FUEL_ZONE', 'GS_FUEL_ZONE_DESC', 'GS_AD_GROUP_DESC', 'GS_PRICING_ZONE_DESC']

In [46]:
Customer_master_columns = "PARTY_SITE_ID, STORE_NBR, STORE_NAME, STORE_STATUS, STORE_BILL_TO_FLAG, STORE_SHIP_TO_FLAG, ACCT_ID, ACCT_NBR, ACCT_NAME, ACCT_STATUS, ACCT_CUST_CLASS_CODE, ACCT_CREATION_DATE, CHAIN_NBR, CHAIN_NAME, CHAIN_SHORT_NAME, CHAIN_INACTIVE_DATE, START_CUST_NBR, STRT_CUST_NBR2, END_CUST_NBR, END_CUST_NBR2, PRIVATE_LABEL_OFFSET, SUB_AUTH_OFFST, AD_START_DAY_OF_WEEK, COMPANY_CODE, HQ_CUST_NBR, DIVISION_NBR, DIVISION_NAME, EBS_GL_CUST_GROUP_NBR, EBS_GL_CUST_GROUP_NAME, STORE_GROUP_NBR, STORE_GROUP_NAME, GROUP_BUY_NBR, STORE_CREATION_DATE, STORE_INACTIVE_DATE, STORE_LAST_UPDATE_DATE, LOCATION_ID, STORE_ADDRESS1, STORE_ADDRESS2, STORE_ADDRESS3, STORE_ADDRESS4, STORE_CITY, STORE_POSTAL_CODE, STORE_STATE, STORE_PROVINCE, STORE_COUNTY, STORE_COUNTRY, STORE_TELEPHONE_NBR, CUST_STORE_NBR, CUST_ACCT_PROFILE_ID, PAY_TERMS, PAY_TERM_DESC, PAY_TERM_START_DATE, PAY_TERM_END_DATE, COLLECTOR_NAME, STATEMENT_CYCLE_NAME, ALT_CUST_NBR, BASE_CUST_NBR, CUST_STATEMENT_FORMAT, PACA_FLAG, TOBACCO_BILLABLE_FLAG, TOBACCO_REBATE, ZONE_NBR, MILITARY_DODAAC, SALES_REPRESENTATIVE, BILL_TO_STORE_NBR, BILL_TO_STORE_NAME, REQUEST_ID, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_LOGIN, PSUEDOEPHEDRINE_FLAG, CALL_FOR_CUSTOMER, CIGARETTE_LICENSE, SMALL_PACK, CIGARETTE_VALIDATION, AWI_CDH_CUSTOMER_CLASS, GAS_REWARDS, MILES, PRINT_STMTS, AWI_CDH_RACK_SERVICE, RETAIL_TYPE, TAX_EXEMPT, ADV_FLAG_7, ADV_FLAG6, BB_AD_PLAN, AD_COMMENTS, ADV_FLAG5, CONFO_AD_PLAN, DEFAULT_TRIP, CATALOG10, AWI_PRINT_BULLETIN, AWI_SIGN_KIT, SURVEYS, ADV_FLAG8, AWI_AD_OFFSET, AGNE_CUSTOMER, CONFO, HBA_GM_FLAG, HBA_GM_DISC_OVERIDE, HBA_GM_DISC, ITEM_ALLOWANCE, COD, SERV_CHARGE, SINGLE_PICK, AWI_CUSTOMER_TYPE, MULTI_STORE_NUMBER, EIGHT_WEEK_BB, BB_MOD_PROGRAM, KPC_END, KPC_RETAIL_ZONE, KPC_START, AWI_PRODUCT, SPECIALTY_FOODS, D_COST_PLUS_BRACKET_FLAG, D_COST_PLUS_BRACKET_NUMBER, D_DEPARTMENT, D_MERCHANDISER, D_PRICING_FLAG, D_SALESMAN, D_SKID_ROUNDING_FLAG, SY_COST_PLUS_BRACKET_FLAG, SY_COST_PLUS_BRACKET_NUMBER, SY_DEPARTMENT, SY_MERCHANDISER, SY_PRICING_FLAG, SY_SALESMAN, SY_SKID_ROUNDING_FLAG, M_COST_PLUS_BRACKET_FLAG, M_COST_PLUS_BRACKET_NUMBER, M_DEPARTMENT, M_MERCHANDISER, M_PRICING_FLAG, M_SALESMAN, M_SKID_ROUNDING_FLAG, P_COST_PLUS_BRACKET_FLAG, P_COST_PLUS_BRACKET_NUMBER, P_DEPARTMENT, P_MERCHANDISER, P_PRICING_FLAG, P_SALESMAN, P_SKID_ROUNDING_FLAG, GM_COST_PLUS_BRACKET_FLAG, GM_COST_PLUS_BRACKET_NUMBER, GM_DEPARTMENT, GM_MERCHANDISER, GM_PRICING_FLAG, GM_SALESMAN, GM_SKID_ROUNDING_FLAG, C_COST_PLUS_BRACKET_FLAG, C_COST_PLUS_BRACKET_NUMBER, C_DEPARTMENT, C_MERCHANDISER, C_PRICING_FLAG, C_SALESMAN, C_SKID_ROUNDING_FLAG, F_COST_PLUS_BRACKET_FLAG, F_COST_PLUS_BRACKET_NUMBER, F_DEPARTMENT, F_MERCHANDISER, F_PRICING_FLAG, F_SALESMAN, F_SKID_ROUNDING_FLAG, RG_COST_PLUS_BRACKET_FLAG, RG_COST_PLUS_BRACKET_NUMBER, RG_DEPARTMENT, RG_MERCHANDISER, RG_PRICING_FLAG, RG_SALESMAN, RG_SKID_ROUNDING_FLAG, DSD_VENDOR, PRIMARY_CONTACT_NAME, PRIMARY_CONTACT_PHONE_NBR, PRIMARY_CONTACT_EMAIL_ADDR, CUSTOMER_GROUP, STORE_GROUP, FINANCE_CHARGES, INTEREST_RATE, PAYMENT_GRACE_DAYS, INTEREST_PERIOD_DAYS, STATEMENT_ADDRESS1, STATEMENT_CITY, STATEMENT_STATE, STATEMENT_ZIP, FINANCE_CHARGE_EFFECTIVE_DATE, SUMMARY_STMT_FORMAT, DELINQUENT_START_DATE, AR_SEGMENT_GROUP, AR_GROUP_NAME, IMPORTED_SOURCE, REMITTANCE_ADDR, STATEMENT_TOLRNCE, INVOICE_TOLRNCE, SALES_REP, RISK_TIER, GS_RETAIL_ACCTNG_REPORT, STATEMENT_LEVEL, RELATED_CUST_LOCKBOX_APPLLY, SEND_ACH_NOTIFTN, STOCK_NAME, MULTI_STORE, EFT, PICKUP_DAY, PAY_DUE_DAY, CREDIT_HOLD, PAYMENT_TERMS, CREDIT_GROUP, BLANK_CHECK_CUSTOMER, AD_PLAN_GROUP, AWI_PARTY_SITE_ID, AWI_MULTI_STORE_NBR, PATRONAGE_NBR, PRINT_STATEMENTS, STATEMENT_INSTRUCTIONS, SEND_TO_AWI_CDH_FLG, CM_BILLING_CYCLE, CM_TERMS, CM_NP_XFER_FLAG, CM_PRINT_STMT, CM_RET_ACCT_STMT, CM_STMT_COPIES, CM_GROUP_CODE, CM_PAYMENT_METHOD, CM_STMT_LABELS, CM_PAYMENT_DUE_DAYS, CM_SUB_STORE, CM_CUST_XREF_NO, STMT_ADJ_GROUP_CODE, CUST_CODE_XREF, SITE_PICK_SLIP_REQ, SITE_PICK_SLIP_REQ_DISP, SITE_RANK, ACC_SUBS, REJ_REASON, MAX_VOL_PALL, ITEM_PAL_ROUND, LOG_ORD_QTY, MIN_ORD_QTY, ENFORCE_DEPT, MAX_ORD_QTY, PO_REQ, PO_REQ_DISP, RET_PRC_REQ, RET_PRC_REQ_DISP, CUST_XREF, CUST_XREF_DISP, LEGACY_CUST_NBR, LEGACY_COMPANY, SHIP_TO_SITE_USE_ID, BILL_TO_SITE_USE_ID, HOSTING_DEPT, RETAILER_DEPT, CONTACT_INFO, STORE_MANAGER, STORE_OWNER, STORE_TYPE, ACCEPT_SUBS, INT_PO_REQ, LAST_BILL_DATE, DIVISION_ID, REGION, DELEGATE_AUTRIZTN_FLG, AISLE_LIMIT, ACCT_TYPE, OLD_STORE_NBR, GS_DASH_0, GS_DASH_0_DESCRIPTION, GS_DASH_1, GS_DASH_1_DESCRIPTION, GS_DASH_2, GS_DASH_2_DESCRIPTION, GS_DASH_3, GS_DASH_3_DESCRIPTION, GS_DASH_4, GS_DASH_4_DESCRIPTION, GS_DASH_5, GS_DASH_5_DESCRIPTION, GS_DASH_6, GS_DASH_6_DESCRIPTION, GS_DASH_7, GS_DASH_7_DESCRIPTION, GS_DASH_8, GS_DASH_8_DESCRIPTION, GS_DASH_9, GS_DASH_9_DESCRIPTION, PLATINUM_DEPT, EXCLUDE_PDF_BKP, GS_ADV_CRD_GROC_RPK_CAYU_PCT, GS_ADV_CRD_MEAT_BULK_PCT, GS_ADV_CRD_CORDER_REPACK_PCT, GS_ADV_CRD_FROZEN_PCT, GS_ADV_CRD_BAKERY_PCT, GS_ADV_CRD_REFRIG_PCT, GS_ADV_CRD_ICREAM_PCT, GS_SALESMAN_NBR, GS_SALESMAN_NAME, GS_CM_DROP_SHIP_FLAG, GS_CM_PAYMENT_METHOD, GS_SELECTION_SERVICE_FEE_FLAG, GS_FRZ_RBT_FLAG, GS_STMT_FROZ_ADJ_FACTOR, GS_STMT_MEAT_ADJ_FACTOR, GS_STMT_GROC_ADJ_FACTOR, GS_NOTE_PAYOFF_CREDIT_RATE, GS_SALES_ADJ_REBATE_RATE, GS_TRANSFER_BAL_DASH_NBR, GS_CUST_CROSS_REF_DASH_NBR, GS_REBATE_CHECK, GS_GROUP_CODE_DESC, GS_PORTAL_FOLDER_NBR, STORE_FAX_NBR, GS_AUD_GROUP, CREDIT_LIMIT, GS_AD_GROUP, GS_TPR_GROUP, GS_GBY_GROUP, GS_PRICING_ZONE, GS_MAP_CD, GS_MAP_CD_LTR, GS_VENDOR_PACK_IND, GS_SUPER_SERVE, GS_NABISCO, GS_WILL_CALL, SWELL, HQ_FLAG, GS_PRIMARY_SHIP_FLAG, GS_FUEL_ZONE, GS_FUEL_ZONE_DESC, GS_AD_GROUP_DESC, GS_PRICING_ZONE_DESC"
# Split the string into a list of column names
Customer_master_list = Customer_master_columns.split(', ')

# Display the list of column names
print(len(Customer_master_list),Customer_master_list)

331 ['PARTY_SITE_ID', 'STORE_NBR', 'STORE_NAME', 'STORE_STATUS', 'STORE_BILL_TO_FLAG', 'STORE_SHIP_TO_FLAG', 'ACCT_ID', 'ACCT_NBR', 'ACCT_NAME', 'ACCT_STATUS', 'ACCT_CUST_CLASS_CODE', 'ACCT_CREATION_DATE', 'CHAIN_NBR', 'CHAIN_NAME', 'CHAIN_SHORT_NAME', 'CHAIN_INACTIVE_DATE', 'START_CUST_NBR', 'STRT_CUST_NBR2', 'END_CUST_NBR', 'END_CUST_NBR2', 'PRIVATE_LABEL_OFFSET', 'SUB_AUTH_OFFST', 'AD_START_DAY_OF_WEEK', 'COMPANY_CODE', 'HQ_CUST_NBR', 'DIVISION_NBR', 'DIVISION_NAME', 'EBS_GL_CUST_GROUP_NBR', 'EBS_GL_CUST_GROUP_NAME', 'STORE_GROUP_NBR', 'STORE_GROUP_NAME', 'GROUP_BUY_NBR', 'STORE_CREATION_DATE', 'STORE_INACTIVE_DATE', 'STORE_LAST_UPDATE_DATE', 'LOCATION_ID', 'STORE_ADDRESS1', 'STORE_ADDRESS2', 'STORE_ADDRESS3', 'STORE_ADDRESS4', 'STORE_CITY', 'STORE_POSTAL_CODE', 'STORE_STATE', 'STORE_PROVINCE', 'STORE_COUNTY', 'STORE_COUNTRY', 'STORE_TELEPHONE_NBR', 'CUST_STORE_NBR', 'CUST_ACCT_PROFILE_ID', 'PAY_TERMS', 'PAY_TERM_DESC', 'PAY_TERM_START_DATE', 'PAY_TERM_END_DATE', 'COLLECTOR_NAME', 'STATEMENT_CYCLE_NAME', 'ALT_CUST_NBR', 'BASE_CUST_NBR', 'CUST_STATEMENT_FORMAT', 'PACA_FLAG', 'TOBACCO_BILLABLE_FLAG', 'TOBACCO_REBATE', 'ZONE_NBR', 'MILITARY_DODAAC', 'SALES_REPRESENTATIVE', 'BILL_TO_STORE_NBR', 'BILL_TO_STORE_NAME', 'REQUEST_ID', 'CREATION_DATE', 'CREATED_BY', 'LAST_UPDATE_DATE', 'LAST_UPDATED_BY', 'LAST_UPDATE_LOGIN', 'PSUEDOEPHEDRINE_FLAG', 'CALL_FOR_CUSTOMER', 'CIGARETTE_LICENSE', 'SMALL_PACK', 'CIGARETTE_VALIDATION', 'AWI_CDH_CUSTOMER_CLASS', 'GAS_REWARDS', 'MILES', 'PRINT_STMTS', 'AWI_CDH_RACK_SERVICE', 'RETAIL_TYPE', 'TAX_EXEMPT', 'ADV_FLAG_7', 'ADV_FLAG6', 'BB_AD_PLAN', 'AD_COMMENTS', 'ADV_FLAG5', 'CONFO_AD_PLAN', 'DEFAULT_TRIP', 'CATALOG10', 'AWI_PRINT_BULLETIN', 'AWI_SIGN_KIT', 'SURVEYS', 'ADV_FLAG8', 'AWI_AD_OFFSET', 'AGNE_CUSTOMER', 'CONFO', 'HBA_GM_FLAG', 'HBA_GM_DISC_OVERIDE', 'HBA_GM_DISC', 'ITEM_ALLOWANCE', 'COD', 'SERV_CHARGE', 'SINGLE_PICK', 'AWI_CUSTOMER_TYPE', 'MULTI_STORE_NUMBER', 'EIGHT_WEEK_BB', 'BB_MOD_PROGRAM', 'KPC_END', 'KPC_RETAIL_ZONE', 'KPC_START', 'AWI_PRODUCT', 'SPECIALTY_FOODS', 'D_COST_PLUS_BRACKET_FLAG', 'D_COST_PLUS_BRACKET_NUMBER', 'D_DEPARTMENT', 'D_MERCHANDISER', 'D_PRICING_FLAG', 'D_SALESMAN', 'D_SKID_ROUNDING_FLAG', 'SY_COST_PLUS_BRACKET_FLAG', 'SY_COST_PLUS_BRACKET_NUMBER', 'SY_DEPARTMENT', 'SY_MERCHANDISER', 'SY_PRICING_FLAG', 'SY_SALESMAN', 'SY_SKID_ROUNDING_FLAG', 'M_COST_PLUS_BRACKET_FLAG', 'M_COST_PLUS_BRACKET_NUMBER', 'M_DEPARTMENT', 'M_MERCHANDISER', 'M_PRICING_FLAG', 'M_SALESMAN', 'M_SKID_ROUNDING_FLAG', 'P_COST_PLUS_BRACKET_FLAG', 'P_COST_PLUS_BRACKET_NUMBER', 'P_DEPARTMENT', 'P_MERCHANDISER', 'P_PRICING_FLAG', 'P_SALESMAN', 'P_SKID_ROUNDING_FLAG', 'GM_COST_PLUS_BRACKET_FLAG', 'GM_COST_PLUS_BRACKET_NUMBER', 'GM_DEPARTMENT', 'GM_MERCHANDISER', 'GM_PRICING_FLAG', 'GM_SALESMAN', 'GM_SKID_ROUNDING_FLAG', 'C_COST_PLUS_BRACKET_FLAG', 'C_COST_PLUS_BRACKET_NUMBER', 'C_DEPARTMENT', 'C_MERCHANDISER', 'C_PRICING_FLAG', 'C_SALESMAN', 'C_SKID_ROUNDING_FLAG', 'F_COST_PLUS_BRACKET_FLAG', 'F_COST_PLUS_BRACKET_NUMBER', 'F_DEPARTMENT', 'F_MERCHANDISER', 'F_PRICING_FLAG', 'F_SALESMAN', 'F_SKID_ROUNDING_FLAG', 'RG_COST_PLUS_BRACKET_FLAG', 'RG_COST_PLUS_BRACKET_NUMBER', 'RG_DEPARTMENT', 'RG_MERCHANDISER', 'RG_PRICING_FLAG', 'RG_SALESMAN', 'RG_SKID_ROUNDING_FLAG', 'DSD_VENDOR', 'PRIMARY_CONTACT_NAME', 'PRIMARY_CONTACT_PHONE_NBR', 'PRIMARY_CONTACT_EMAIL_ADDR', 'CUSTOMER_GROUP', 'STORE_GROUP', 'FINANCE_CHARGES', 'INTEREST_RATE', 'PAYMENT_GRACE_DAYS', 'INTEREST_PERIOD_DAYS', 'STATEMENT_ADDRESS1', 'STATEMENT_CITY', 'STATEMENT_STATE', 'STATEMENT_ZIP', 'FINANCE_CHARGE_EFFECTIVE_DATE', 'SUMMARY_STMT_FORMAT', 'DELINQUENT_START_DATE', 'AR_SEGMENT_GROUP', 'AR_GROUP_NAME', 'IMPORTED_SOURCE', 'REMITTANCE_ADDR', 'STATEMENT_TOLRNCE', 'INVOICE_TOLRNCE', 'SALES_REP', 'RISK_TIER', 'GS_RETAIL_ACCTNG_REPORT', 'STATEMENT_LEVEL', 'RELATED_CUST_LOCKBOX_APPLLY', 'SEND_ACH_NOTIFTN', 'STOCK_NAME', 'MULTI_STORE', 'EFT', 'PICKUP_DAY', 'PAY_DUE_DAY', 'CREDIT_HOLD', 'PAYMENT_TERMS', 'CREDIT_GROUP', 'BLANK_CHECK_CUSTOMER', 'AD_PLAN_GROUP', 'AWI_PARTY_SITE_ID', 'AWI_MULTI_STORE_NBR', 'PATRONAGE_NBR', 'PRINT_STATEMENTS', 'STATEMENT_INSTRUCTIONS', 'SEND_TO_AWI_CDH_FLG', 'CM_BILLING_CYCLE', 'CM_TERMS', 'CM_NP_XFER_FLAG', 'CM_PRINT_STMT', 'CM_RET_ACCT_STMT', 'CM_STMT_COPIES', 'CM_GROUP_CODE', 'CM_PAYMENT_METHOD', 'CM_STMT_LABELS', 'CM_PAYMENT_DUE_DAYS', 'CM_SUB_STORE', 'CM_CUST_XREF_NO', 'STMT_ADJ_GROUP_CODE', 'CUST_CODE_XREF', 'SITE_PICK_SLIP_REQ', 'SITE_PICK_SLIP_REQ_DISP', 'SITE_RANK', 'ACC_SUBS', 'REJ_REASON', 'MAX_VOL_PALL', 'ITEM_PAL_ROUND', 'LOG_ORD_QTY', 'MIN_ORD_QTY', 'ENFORCE_DEPT', 'MAX_ORD_QTY', 'PO_REQ', 'PO_REQ_DISP', 'RET_PRC_REQ', 'RET_PRC_REQ_DISP', 'CUST_XREF', 'CUST_XREF_DISP', 'LEGACY_CUST_NBR', 'LEGACY_COMPANY', 'SHIP_TO_SITE_USE_ID', 'BILL_TO_SITE_USE_ID', 'HOSTING_DEPT', 'RETAILER_DEPT', 'CONTACT_INFO', 'STORE_MANAGER', 'STORE_OWNER', 'STORE_TYPE', 'ACCEPT_SUBS', 'INT_PO_REQ', 'LAST_BILL_DATE', 'DIVISION_ID', 'REGION', 'DELEGATE_AUTRIZTN_FLG', 'AISLE_LIMIT', 'ACCT_TYPE', 'OLD_STORE_NBR', 'GS_DASH_0', 'GS_DASH_0_DESCRIPTION', 'GS_DASH_1', 'GS_DASH_1_DESCRIPTION', 'GS_DASH_2', 'GS_DASH_2_DESCRIPTION', 'GS_DASH_3', 'GS_DASH_3_DESCRIPTION', 'GS_DASH_4', 'GS_DASH_4_DESCRIPTION', 'GS_DASH_5', 'GS_DASH_5_DESCRIPTION', 'GS_DASH_6', 'GS_DASH_6_DESCRIPTION', 'GS_DASH_7', 'GS_DASH_7_DESCRIPTION', 'GS_DASH_8', 'GS_DASH_8_DESCRIPTION', 'GS_DASH_9', 'GS_DASH_9_DESCRIPTION', 'PLATINUM_DEPT', 'EXCLUDE_PDF_BKP', 'GS_ADV_CRD_GROC_RPK_CAYU_PCT', 'GS_ADV_CRD_MEAT_BULK_PCT', 'GS_ADV_CRD_CORDER_REPACK_PCT', 'GS_ADV_CRD_FROZEN_PCT', 'GS_ADV_CRD_BAKERY_PCT', 'GS_ADV_CRD_REFRIG_PCT', 'GS_ADV_CRD_ICREAM_PCT', 'GS_SALESMAN_NBR', 'GS_SALESMAN_NAME', 'GS_CM_DROP_SHIP_FLAG', 'GS_CM_PAYMENT_METHOD', 'GS_SELECTION_SERVICE_FEE_FLAG', 'GS_FRZ_RBT_FLAG', 'GS_STMT_FROZ_ADJ_FACTOR', 'GS_STMT_MEAT_ADJ_FACTOR', 'GS_STMT_GROC_ADJ_FACTOR', 'GS_NOTE_PAYOFF_CREDIT_RATE', 'GS_SALES_ADJ_REBATE_RATE', 'GS_TRANSFER_BAL_DASH_NBR', 'GS_CUST_CROSS_REF_DASH_NBR', 'GS_REBATE_CHECK', 'GS_GROUP_CODE_DESC', 'GS_PORTAL_FOLDER_NBR', 'STORE_FAX_NBR', 'GS_AUD_GROUP', 'CREDIT_LIMIT', 'GS_AD_GROUP', 'GS_TPR_GROUP', 'GS_GBY_GROUP', 'GS_PRICING_ZONE', 'GS_MAP_CD', 'GS_MAP_CD_LTR', 'GS_VENDOR_PACK_IND', 'GS_SUPER_SERVE', 'GS_NABISCO', 'GS_WILL_CALL', 'SWELL', 'HQ_FLAG', 'GS_PRIMARY_SHIP_FLAG', 'GS_FUEL_ZONE', 'GS_FUEL_ZONE_DESC', 'GS_AD_GROUP_DESC', 'GS_PRICING_ZONE_DESC']

In [47]:
# Convert lists to sets
audit_columns_set = set(Audit_columns_list)
customer_master_set = set(Customer_master_list)

# Find columns present in Audit_columns_list but not in Customer_master_list
columns_only_in_audit = audit_columns_set - customer_master_set

# Find columns present in Customer_master_list but not in Audit_columns_list
columns_only_in_customer = customer_master_set - audit_columns_set

# Display the results
print("Columns present only in Audit_columns_list:", columns_only_in_audit)
print("Columns present only in Customer_master_list:", columns_only_in_customer)
#This will output the columns that are unique to each list. The - operator is used to find the set difference, and the result is then printed.

Columns present only in Audit_columns_list: set()
Columns present only in Customer_master_list: set()

In [43]:
audit_columns_set

{'ACCEPT_SUBS',
 'ACCT_CREATION_DATE',
 'ACCT_CUST_CLASS_CODE',
 'ACCT_ID',
 'ACCT_NAME',
 'ACCT_NBR',
 'ACCT_STATUS',
 'ACCT_TYPE',
 'ACC_SUBS',
 'ADV_FLAG5',
 'ADV_FLAG6',
 'ADV_FLAG8',
 'ADV_FLAG_7',
 'AD_COMMENTS',
 'AD_PLAN_GROUP',
 'AD_START_DAY_OF_WEEK',
 'AGNE_CUSTOMER',
 'AISLE_LIMIT',
 'ALT_CUST_NBR',
 'AR_GROUP_NAME',
 'AR_SEGMENT_GROUP',
 'AWI_AD_OFFSET',
 'AWI_CDH_CUSTOMER_CLASS',
 'AWI_CDH_RACK_SERVICE',
 'AWI_CUSTOMER_TYPE',
 'AWI_MULTI_STORE_NBR',
 'AWI_PARTY_SITE_ID',
 'AWI_PRINT_BULLETIN',
 'AWI_PRODUCT',
 'AWI_SIGN_KIT',
 'BASE_CUST_NBR',
 'BB_AD_PLAN',
 'BB_MOD_PROGRAM',
 'BILL_TO_SITE_USE_ID',
 'BILL_TO_STORE_NAME',
 'BILL_TO_STORE_NBR',
 'BLANK_CHECK_CUSTOMER',
 'CALL_FOR_CUSTOMER',
 'CATALOG10',
 'CHAIN_INACTIVE_DATE',
 'CHAIN_NAME',
 'CHAIN_NBR',
 'CHAIN_SHORT_NAME',
 'CIGARETTE_LICENSE',
 'CIGARETTE_VALIDATION',
 'CM_BILLING_CYCLE',
 'CM_CUST_XREF_NO',
 'CM_GROUP_CODE',
 'CM_NP_XFER_FLAG',
 'CM_PAYMENT_DUE_DAYS',
 'CM_PAYMENT_METHOD',
 'CM_PRINT_STMT',
 'CM_RET_ACCT_STMT',
 'CM_STMT_COPIES',
 'CM_STMT_LABELS',
 'CM_SUB_STORE',
 'CM_TERMS',
 'COD',
 'COLLECTOR_NAME',
 'COMPANY_CODE',
 'CONFO',
 'CONFO_AD_PLAN',
 'CONTACT_INFO',
 'CREATED_BY',
 'CREATION_DATE',
 'CREDIT_GROUP',
 'CREDIT_HOLD',
 'CREDIT_LIMIT',
 'CUSTOMER_GROUP',
 'CUST_ACCT_PROFILE_ID',
 'CUST_CODE_XREF',
 'CUST_STATEMENT_FORMAT',
 'CUST_STORE_NBR',
 'CUST_XREF',
 'CUST_XREF_DISP',
 'C_COST_PLUS_BRACKET_FLAG',
 'C_COST_PLUS_BRACKET_NUMBER',
 'C_DEPARTMENT',
 'C_MERCHANDISER',
 'C_PRICING_FLAG',
 'C_SALESMAN',
 'C_SKID_ROUNDING_FLAG',
 'DEFAULT_TRIP',
 'DELEGATE_AUTRIZTN_FLG',
 'DELINQUENT_START_DATE',
 'DIVISION_ID',
 'DIVISION_NAME',
 'DIVISION_NBR',
 'DSD_VENDOR',
 'D_COST_PLUS_BRACKET_FLAG',
 'D_COST_PLUS_BRACKET_NUMBER',
 'D_DEPARTMENT',
 'D_MERCHANDISER',
 'D_PRICING_FLAG',
 'D_SALESMAN',
 'D_SKID_ROUNDING_FLAG',
 'EBS_GL_CUST_GROUP_NAME',
 'EBS_GL_CUST_GROUP_NBR',
 'EFT',
 'EIGHT_WEEK_BB',
 'END_CUST_NBR',
 'END_CUST_NBR2',
 'ENFORCE_DEPT',
 'EXCLUDE_PDF_BKP',
 'FINANCE_CHARGES',
 'FINANCE_CHARGE_EFFECTIVE_DATE',
 'F_COST_PLUS_BRACKET_FLAG',
 'F_COST_PLUS_BRACKET_NUMBER',
 'F_DEPARTMENT',
 'F_MERCHANDISER',
 'F_PRICING_FLAG',
 'F_SALESMAN',
 'F_SKID_ROUNDING_FLAG',
 'GAS_REWARDS',
 'GM_COST_PLUS_BRACKET_FLAG',
 'GM_COST_PLUS_BRACKET_NUMBER',
 'GM_DEPARTMENT',
 'GM_MERCHANDISER',
 'GM_PRICING_FLAG',
 'GM_SALESMAN',
 'GM_SKID_ROUNDING_FLAG',
 'GROUP_BUY_NBR',
 'GS_ADV_CRD_BAKERY_PCT',
 'GS_ADV_CRD_CORDER_REPACK_PCT',
 'GS_ADV_CRD_FROZEN_PCT',
 'GS_ADV_CRD_GROC_RPK_CAYU_PCT',
 'GS_ADV_CRD_ICREAM_PCT',
 'GS_ADV_CRD_MEAT_BULK_PCT',
 'GS_ADV_CRD_REFRIG_PCT',
 'GS_AD_GROUP',
 'GS_AD_GROUP_DESC',
 'GS_AUD_GROUP',
 'GS_CM_DROP_SHIP_FLAG',
 'GS_CM_PAYMENT_METHOD',
 'GS_CUST_CROSS_REF_DASH_NBR',
 'GS_DASH_0',
 'GS_DASH_0_DESCRIPTION',
 'GS_DASH_1',
 'GS_DASH_1_DESCRIPTION',
 'GS_DASH_2',
 'GS_DASH_2_DESCRIPTION',
 'GS_DASH_3',
 'GS_DASH_3_DESCRIPTION',
 'GS_DASH_4',
 'GS_DASH_4_DESCRIPTION',
 'GS_DASH_5',
 'GS_DASH_5_DESCRIPTION',
 'GS_DASH_6',
 'GS_DASH_6_DESCRIPTION',
 'GS_DASH_7',
 'GS_DASH_7_DESCRIPTION',
 'GS_DASH_8',
 'GS_DASH_8_DESCRIPTION',
 'GS_DASH_9',
 'GS_DASH_9_DESCRIPTION',
 'GS_FRZ_RBT_FLAG',
 'GS_FUEL_ZONE',
 'GS_FUEL_ZONE_DESC',
 'GS_GBY_GROUP',
 'GS_GROUP_CODE_DESC',
 'GS_MAP_CD',
 'GS_MAP_CD_LTR',
 'GS_NABISCO',
 'GS_NOTE_PAYOFF_CREDIT_RATE',
 'GS_PORTAL_FOLDER_NBR',
 'GS_PRICING_ZONE',
 'GS_PRICING_ZONE_DESC',
 'GS_PRIMARY_SHIP_FLAG',
 'GS_REBATE_CHECK',
 'GS_RETAIL_ACCTNG_REPORT',
 'GS_SALESMAN_NAME',
 'GS_SALESMAN_NBR',
 'GS_SALES_ADJ_REBATE_RATE',
 'GS_SELECTION_SERVICE_FEE_FLAG',
 'GS_STMT_FROZ_ADJ_FACTOR',
 'GS_STMT_GROC_ADJ_FACTOR',
 'GS_STMT_MEAT_ADJ_FACTOR',
 'GS_SUPER_SERVE',
 'GS_TPR_GROUP',
 'GS_TRANSFER_BAL_DASH_NBR',
 'GS_VENDOR_PACK_IND',
 'GS_WILL_CALL',
 'HBA_GM_DISC',
 'HBA_GM_DISC_OVERIDE',
 'HBA_GM_FLAG',
 'HOSTING_DEPT',
 'HQ_CUST_NBR',
 'HQ_FLAG',
 'IMPORTED_SOURCE',
 'INTEREST_PERIOD_DAYS',
 'INTEREST_RATE',
 'INT_PO_REQ',
 'INVOICE_TOLRNCE',
 'ITEM_ALLOWANCE',
 'ITEM_PAL_ROUND',
 'KPC_END',
 'KPC_RETAIL_ZONE',
 'KPC_START',
 'LAST_BILL_DATE',
 'LAST_UPDATED_BY',
 'LAST_UPDATE_DATE',
 'LAST_UPDATE_LOGIN',
 'LEGACY_COMPANY',
 'LEGACY_CUST_NBR',
 'LOCATION_ID',
 'LOG_ORD_QTY',
 'MAX_ORD_QTY',
 'MAX_VOL_PALL',
 'MILES',
 'MILITARY_DODAAC',
 'MIN_ORD_QTY',
 'MULTI_STORE',
 'MULTI_STORE_NUMBER',
 'M_COST_PLUS_BRACKET_FLAG',
 'M_COST_PLUS_BRACKET_NUMBER',
 'M_DEPARTMENT',
 'M_MERCHANDISER',
 'M_PRICING_FLAG',
 'M_SALESMAN',
 'M_SKID_ROUNDING_FLAG',
 'OLD_STORE_NBR',
 'PACA_FLAG',
 'PARTY_SITE_ID',
 'PATRONAGE_NBR',
 'PAYMENT_GRACE_DAYS',
 'PAYMENT_TERMS',
 'PAY_DUE_DAY',
 'PAY_TERMS',
 'PAY_TERM_DESC',
 'PAY_TERM_END_DATE',
 'PAY_TERM_START_DATE',
 'PICKUP_DAY',
 'PLATINUM_DEPT',
 'PO_REQ',
 'PO_REQ_DISP',
 'PRIMARY_CONTACT_EMAIL_ADDR',
 'PRIMARY_CONTACT_NAME',
 'PRIMARY_CONTACT_PHONE_NBR',
 'PRINT_STATEMENTS',
 'PRINT_STMTS',
 'PRIVATE_LABEL_OFFSET',
 'PSUEDOEPHEDRINE_FLAG',
 'P_COST_PLUS_BRACKET_FLAG',
 'P_COST_PLUS_BRACKET_NUMBER',
 'P_DEPARTMENT',
 'P_MERCHANDISER',
 'P_PRICING_FLAG',
 'P_SALESMAN',
 'P_SKID_ROUNDING_FLAG',
 'REGION',
 'REJ_REASON',
 'RELATED_CUST_LOCKBOX_APPLLY',
 'REMITTANCE_ADDR',
 'REQUEST_ID',
 'RETAILER_DEPT',
 'RETAIL_TYPE',
 'RET_PRC_REQ',
 'RET_PRC_REQ_DISP',
 'RG_COST_PLUS_BRACKET_FLAG',
 'RG_COST_PLUS_BRACKET_NUMBER',
 'RG_DEPARTMENT',
 'RG_MERCHANDISER',
 'RG_PRICING_FLAG',
 'RG_SALESMAN',
 'RG_SKID_ROUNDING_FLAG',
 'RISK_TIER',
 'SALES_REP',
 'SALES_REPRESENTATIVE',
 'SEND_ACH_NOTIFTN',
 'SEND_TO_AWI_CDH_FLG',
 'SERV_CHARGE',
 'SHIP_TO_SITE_USE_ID',
 'SINGLE_PICK',
 'SITE_PICK_SLIP_REQ',
 'SITE_PICK_SLIP_REQ_DISP',
 'SITE_RANK',
 'SMALL_PACK',
 'SPECIALTY_FOODS',
 'START_CUST_NBR',
 'STATEMENT_ADDRESS1',
 'STATEMENT_CITY',
 'STATEMENT_CYCLE_NAME',
 'STATEMENT_INSTRUCTIONS',
 'STATEMENT_LEVEL',
 'STATEMENT_STATE',
 'STATEMENT_TOLRNCE',
 'STATEMENT_ZIP',
 'STMT_ADJ_GROUP_CODE',
 'STOCK_NAME',
 'STORE_ADDRESS1',
 'STORE_ADDRESS2',
 'STORE_ADDRESS3',
 'STORE_ADDRESS4',
 'STORE_BILL_TO_FLAG',
 'STORE_CITY',
 'STORE_COUNTRY',
 'STORE_COUNTY',
 'STORE_CREATION_DATE',
 'STORE_FAX_NBR',
 'STORE_GROUP',
 'STORE_GROUP_NAME',
 'STORE_GROUP_NBR',
 'STORE_INACTIVE_DATE',
 'STORE_LAST_UPDATE_DATE',
 'STORE_MANAGER',
 'STORE_NAME',
 'STORE_NBR',
 'STORE_OWNER',
 'STORE_POSTAL_CODE',
 'STORE_PROVINCE',
 'STORE_SHIP_TO_FLAG',
 'STORE_STATE',
 'STORE_STATUS',
 'STORE_TELEPHONE_NBR',
 'STORE_TYPE',
 'STRT_CUST_NBR2',
 'SUB_AUTH_OFFST',
 'SUMMARY_STMT_FORMAT',
 'SURVEYS',
 'SWELL',
 'SY_COST_PLUS_BRACKET_FLAG',
 'SY_COST_PLUS_BRACKET_NUMBER',
 'SY_DEPARTMENT',
 'SY_MERCHANDISER',
 'SY_PRICING_FLAG',
 'SY_SALESMAN',
 'SY_SKID_ROUNDING_FLAG',
 'TAX_EXEMPT',
 'TOBACCO_BILLABLE_FLAG',
 'TOBACCO_REBATE',
 'ZONE_NBR'}